
package com.htv.smartfarm.gateway.inventory;

import com.htv.smartfarm.gateway.context.GatewayCorrelationContext;
import com.htv.smartfarm.gateway.grpc.GatewayGrpcExceptionMapper;
import com.htv.smartfarm.gateway.identity.GatewayRequestContextFactory;
import com.htv.smartfarm.gateway.identity.ServiceTokenClient;
import com.htv.smartfarm.proto.common.v1.PageRequest;
import com.htv.smartfarm.proto.common.v1.Quantity;
import com.htv.smartfarm.proto.inventory.v1.*;
import com.htv.smartfarm.security.grpc.BearerCallCredentials;
import io.grpc.StatusRuntimeException;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.TimeUnit;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.web.bind.annotation.*;
import reactor.core.publisher.Mono;
import reactor.core.scheduler.Schedulers;

@RestController
@RequestMapping("/api/v1/inventory")
public class InventoryController {
    public record CreateItemBody(String sku,String name,String unit,String category,String reorderThreshold) { }
    public record UpdateItemBody(String name,String unit,String category,String reorderThreshold) { }
    public record UpdateWarehouseBody(String name,String description,String address) { }
    public record IssueBody(String lotId,String quantity,String unit,String referenceId) { }
    public record CreateWarehouseBody(String warehouseId,String farmId,String code,String name,String description,String address) { }
    public record ReceiveBody(String itemId,String farmId,String warehouseId,String lotId,String quantity,String unit,String referenceId) { }
    public record AdjustBody(String quantity,String unit,String reason) { }
    private static final String AUDIENCE="smartfarm-inventory";
    private final InventoryServiceGrpc.InventoryServiceBlockingStub base;
    private final ServiceTokenClient tokens; private final GatewayRequestContextFactory contexts;
    private final GatewayGrpcExceptionMapper errors; private final long deadline;
    public InventoryController(InventoryServiceGrpc.InventoryServiceBlockingStub gwInventoryStub,ServiceTokenClient tokens,GatewayRequestContextFactory contexts,GatewayGrpcExceptionMapper errors,@Value("${smartfarm.gateway.grpc.inventory-deadline:5s}")Duration deadline){this.base=gwInventoryStub;this.tokens=tokens;this.contexts=contexts;this.errors=errors;this.deadline=deadline.toMillis();}

    @GetMapping("/items") @PreAuthorize("hasAuthority('SCOPE_inventory:read')")
    public Mono<Map<String,Object>> items(@AuthenticationPrincipal Jwt jwt,@RequestParam(defaultValue="")String query,@RequestParam(required=false)String category,@RequestParam(defaultValue="50")int size){return call("ListItems",jwt,null,()->{var c=contexts.create(jwt,null,null);var b=ListItemsRequest.newBuilder().setContext(c).setQuery(query).setPage(PageRequest.newBuilder().setPageSize(size));if(category!=null&&!category.isBlank())b.setCategory(ItemCategory.valueOf(category.startsWith("ITEM_CATEGORY_")?category:"ITEM_CATEGORY_"+category.toUpperCase()));var r=stub(jwt,c.getCorrelationId()).listItems(b.build());Map<String,Object>m=new LinkedHashMap<>();m.put("items",r.getItemsList().stream().map(InventoryController::item).toList());m.put("nextPageToken",r.getPage().getNextPageToken());return m;});}
    @GetMapping("/items/{id}") @PreAuthorize("hasAuthority('SCOPE_inventory:read')") public Mono<Map<String,Object>> item(@AuthenticationPrincipal Jwt jwt,@PathVariable String id){return call("GetItem",jwt,null,()->{var c=contexts.create(jwt,null,null);return item(stub(jwt,c.getCorrelationId()).getItem(GetItemRequest.newBuilder().setContext(c).setItemId(id).build()).getItem());});}
    @PostMapping("/items") @PreAuthorize("hasAuthority('SCOPE_inventory:write')") public Mono<Map<String,Object>> createItem(@AuthenticationPrincipal Jwt jwt,@RequestHeader("Idempotency-Key")String key,@RequestHeader(value="X-Correlation-Id",required=false)String correlation,@RequestBody CreateItemBody x){return call("CreateItem",jwt,correlation,()->{var c=contexts.create(jwt,GatewayCorrelationContext.normalize(correlation),key);var i=InventoryItem.newBuilder().setSku(x.sku()).setName(x.name()).setUnit(x.unit()).setCategory(category(x.category()));if(x.reorderThreshold()!=null&&!x.reorderThreshold().isBlank())i.setReorderThreshold(q(x.reorderThreshold(),x.unit()));return item(stub(jwt,c.getCorrelationId()).createItem(CreateItemRequest.newBuilder().setContext(c).setItem(i).build()).getItem());});}
    @PutMapping("/items/{id}") @PreAuthorize("hasAuthority('SCOPE_inventory:write')") public Mono<Map<String,Object>> updateItem(@AuthenticationPrincipal Jwt jwt,@PathVariable String id,@RequestBody UpdateItemBody x){return call("UpdateItem",jwt,null,()->{var c=contexts.create(jwt,null,null);return item(stub(jwt,c.getCorrelationId()).updateItem(UpdateItemRequest.newBuilder().setContext(c).setItemId(id).setName(x.name()).setUnit(x.unit()).setCategory(category(x.category())).setReorderThreshold(q(x.reorderThreshold(),x.unit())).build()).getItem());});}
    @DeleteMapping("/items/{id}") @PreAuthorize("hasAuthority('SCOPE_inventory:write')") public Mono<Map<String,Object>> disableItem(@AuthenticationPrincipal Jwt jwt,@PathVariable String id){return call("SetItemStatus",jwt,null,()->{var c=contexts.create(jwt,null,null);return item(stub(jwt,c.getCorrelationId()).setItemStatus(SetItemStatusRequest.newBuilder().setContext(c).setItemId(id).setStatus(ItemStatus.ITEM_STATUS_INACTIVE).build()).getItem());});}
    @PostMapping("/warehouses") @PreAuthorize("hasAuthority('SCOPE_inventory:write')") public Mono<Map<String,Object>> createWarehouse(@AuthenticationPrincipal Jwt jwt,@RequestBody CreateWarehouseBody x){return call("CreateWarehouse",jwt,null,()->{var c=contexts.create(jwt,null,null);var w=Warehouse.newBuilder().setWarehouseId(value(x.warehouseId())).setFarmId(x.farmId()).setCode(x.code()).setName(x.name()).setDescription(value(x.description())).setAddress(value(x.address()));return warehouse(stub(jwt,c.getCorrelationId()).createWarehouse(CreateWarehouseRequest.newBuilder().setContext(c).setWarehouse(w).build()).getWarehouse());});}
    @GetMapping("/warehouses") @PreAuthorize("hasAuthority('SCOPE_inventory:read')") public Mono<Map<String,Object>> warehouses(@AuthenticationPrincipal Jwt jwt,@RequestParam String farmId,@RequestParam(defaultValue="")String query,@RequestParam(defaultValue="50")int size){return call("ListWarehouses",jwt,null,()->{var c=contexts.create(jwt,null,null);var r=stub(jwt,c.getCorrelationId()).listWarehouses(ListWarehousesRequest.newBuilder().setContext(c).setFarmId(farmId).setQuery(query).setPage(PageRequest.newBuilder().setPageSize(size)).build());Map<String,Object>m=new LinkedHashMap<>();m.put("warehouses",r.getWarehousesList().stream().map(InventoryController::warehouse).toList());m.put("nextPageToken",r.getPage().getNextPageToken());return m;});}
    @PutMapping("/warehouses/{id}") @PreAuthorize("hasAuthority('SCOPE_inventory:write')") public Mono<Map<String,Object>> updateWarehouse(@AuthenticationPrincipal Jwt jwt,@PathVariable String id,@RequestBody UpdateWarehouseBody x){return call("UpdateWarehouse",jwt,null,()->{var c=contexts.create(jwt,null,null);return warehouse(stub(jwt,c.getCorrelationId()).updateWarehouse(UpdateWarehouseRequest.newBuilder().setContext(c).setWarehouseId(id).setName(x.name()).setDescription(value(x.description())).setAddress(value(x.address())).build()).getWarehouse());});}
    @DeleteMapping("/warehouses/{id}") @PreAuthorize("hasAuthority('SCOPE_inventory:write')") public Mono<Map<String,Object>> disableWarehouse(@AuthenticationPrincipal Jwt jwt,@PathVariable String id){return call("SetWarehouseStatus",jwt,null,()->{var c=contexts.create(jwt,null,null);return warehouse(stub(jwt,c.getCorrelationId()).setWarehouseStatus(SetWarehouseStatusRequest.newBuilder().setContext(c).setWarehouseId(id).setStatus(WarehouseStatus.WAREHOUSE_STATUS_INACTIVE).build()).getWarehouse());});}
    @GetMapping("/warehouses/{id}") @PreAuthorize("hasAuthority('SCOPE_inventory:read')") public Mono<Map<String,Object>> warehouse(@AuthenticationPrincipal Jwt jwt,@PathVariable String id){return call("GetWarehouse",jwt,null,()->{var c=contexts.create(jwt,null,null);return warehouse(stub(jwt,c.getCorrelationId()).getWarehouse(GetWarehouseRequest.newBuilder().setContext(c).setWarehouseId(id).build()).getWarehouse());});}
    @GetMapping("/warehouses/{id}/items") @PreAuthorize("hasAuthority('SCOPE_inventory:read')") public Mono<Map<String,Object>> warehouseItems(@AuthenticationPrincipal Jwt jwt,@PathVariable String id,@RequestParam(defaultValue="")String query,@RequestParam(defaultValue="false")boolean lowStockOnly,@RequestParam(defaultValue="50")int size){return call("ListWarehouseItems",jwt,null,()->{var c=contexts.create(jwt,null,null);var r=stub(jwt,c.getCorrelationId()).listWarehouseItems(ListWarehouseItemsRequest.newBuilder().setContext(c).setWarehouseId(id).setQuery(query).setLowStockOnly(lowStockOnly).setPage(PageRequest.newBuilder().setPageSize(size)).build());Map<String,Object>m=new LinkedHashMap<>();m.put("warehouse",warehouse(r.getWarehouse()));m.put("items",r.getItemsList().stream().map(InventoryController::stock).toList());return m;});}
    @PostMapping("/receipts") @PreAuthorize("hasAuthority('SCOPE_inventory:write')") public Mono<Map<String,Object>> receive(@AuthenticationPrincipal Jwt jwt,@RequestHeader("Idempotency-Key")String key,@RequestBody ReceiveBody x){return call("ReceiveStock",jwt,null,()->{var c=contexts.create(jwt,null,key);var lot=StockLot.newBuilder().setLotId(value(x.lotId())).setItemId(x.itemId()).setFarmId(x.farmId()).setWarehouseId(x.warehouseId());return movement(stub(jwt,c.getCorrelationId()).receiveStock(ReceiveStockRequest.newBuilder().setContext(c).setLot(lot).setQuantity(q(x.quantity(),x.unit())).setReferenceId(value(x.referenceId())).build()).getMovement());});}
    @PostMapping("/issues") @PreAuthorize("hasAuthority('SCOPE_inventory:write')") public Mono<Map<String,Object>> issue(@AuthenticationPrincipal Jwt jwt,@RequestHeader("Idempotency-Key")String key,@RequestBody IssueBody x){return call("IssueStock",jwt,null,()->{var c=contexts.create(jwt,null,key);return movement(stub(jwt,c.getCorrelationId()).issueStock(IssueStockRequest.newBuilder().setContext(c).setLotId(x.lotId()).setQuantity(q(x.quantity(),x.unit())).setReferenceId(value(x.referenceId())).build()).getMovement());});}
    @PostMapping("/lots/{id}/adjustments") @PreAuthorize("hasAuthority('SCOPE_inventory:write')") public Mono<Map<String,Object>> adjust(@AuthenticationPrincipal Jwt jwt,@RequestHeader("Idempotency-Key")String key,@PathVariable String id,@RequestBody AdjustBody x){return call("AdjustStock",jwt,null,()->{var c=contexts.create(jwt,null,key);return movement(stub(jwt,c.getCorrelationId()).adjustStock(AdjustStockRequest.newBuilder().setContext(c).setLotId(id).setSignedDelta(q(x.quantity(),x.unit())).setReason(value(x.reason())).build()).getMovement());});}
    @GetMapping("/lots/{id}/trace") @PreAuthorize("hasAuthority('SCOPE_inventory:read')") public Mono<Map<String,Object>> trace(@AuthenticationPrincipal Jwt jwt,@PathVariable String id,@RequestParam(defaultValue="50")int size){return call("TraceLot",jwt,null,()->{var c=contexts.create(jwt,null,null);var r=stub(jwt,c.getCorrelationId()).traceLot(TraceLotRequest.newBuilder().setContext(c).setLotId(id).setPage(PageRequest.newBuilder().setPageSize(size)).build());Map<String,Object>m=new LinkedHashMap<>();m.put("lot",Map.of("lotId",r.getLot().getLotId(),"itemId",r.getLot().getItemId(),"farmId",r.getLot().getFarmId(),"warehouseId",r.getLot().getWarehouseId()));m.put("movements",r.getMovementsList().stream().map(InventoryController::movement).toList());return m;});}
    @GetMapping("/balances") @PreAuthorize("hasAuthority('SCOPE_inventory:read')") public Mono<Map<String,Object>> balance(@AuthenticationPrincipal Jwt jwt,@RequestParam String itemId,@RequestParam String warehouseId){return call("GetStockBalance",jwt,null,()->{var c=contexts.create(jwt,null,null);return balance(stub(jwt,c.getCorrelationId()).getStockBalance(GetStockBalanceRequest.newBuilder().setContext(c).setItemId(itemId).setWarehouseId(warehouseId).build()).getBalance());});}
    @GetMapping("/low-stock") @PreAuthorize("hasAuthority('SCOPE_inventory:read')") public Mono<Map<String,Object>> low(@AuthenticationPrincipal Jwt jwt,@RequestParam String farmId,@RequestParam(defaultValue="50")int size){return call("ListLowStock",jwt,null,()->{var c=contexts.create(jwt,null,null);var r=stub(jwt,c.getCorrelationId()).listLowStock(ListLowStockRequest.newBuilder().setContext(c).setFarmId(farmId).setPage(PageRequest.newBuilder().setPageSize(size)).build());return Map.of("balances",r.getBalancesList().stream().map(InventoryController::balance).toList());});}

    private InventoryServiceGrpc.InventoryServiceBlockingStub stub(Jwt jwt,String correlation){String tenant=jwt.getClaimAsString("tenant_id");String token=tokens.tokenFor(AUDIENCE,tenant,jwt.getSubject());return base.withDeadlineAfter(deadline,TimeUnit.MILLISECONDS).withCallCredentials(new BearerCallCredentials(()->token,()->tenant,()->correlation));}
    private <T>Mono<T> call(String op,Jwt jwt,String correlation,java.util.concurrent.Callable<T>fn){return Mono.fromCallable(()->{try{return fn.call();}catch(StatusRuntimeException e){if(e.getStatus().getCode()==io.grpc.Status.Code.UNAUTHENTICATED)tokens.invalidate(AUDIENCE,jwt.getClaimAsString("tenant_id"));throw errors.rest(op,e);}}).subscribeOn(Schedulers.boundedElastic());}
    private static ItemCategory category(String v){if(v==null||v.isBlank())return ItemCategory.ITEM_CATEGORY_OTHER;String n=v.toUpperCase();return ItemCategory.valueOf(n.startsWith("ITEM_CATEGORY_")?n:"ITEM_CATEGORY_"+n);}private static Quantity q(String v,String u){return Quantity.newBuilder().setDecimalValue(v).setUnit(u).build();}private static String value(String v){return v==null?"":v.trim();}
    private static Map<String,Object>item(InventoryItem i){return Map.of("itemId",i.getItemId(),"sku",i.getSku(),"name",i.getName(),"unit",i.getUnit(),"category",i.getCategory().name(),"reorderThreshold",i.getReorderThreshold().getDecimalValue());}
    private static Map<String,Object>warehouse(Warehouse w){return Map.of("warehouseId",w.getWarehouseId(),"farmId",w.getFarmId(),"code",w.getCode(),"name",w.getName(),"status",w.getStatus().name());}
    private static Map<String,Object>stock(WarehouseStockItem i){Map<String,Object>m=new LinkedHashMap<>();m.put("itemId",i.getItemId());m.put("sku",i.getSku());m.put("name",i.getItemName());m.put("unit",i.getUnit());m.put("onHand",i.getOnHand().getDecimalValue());m.put("reserved",i.getReserved().getDecimalValue());m.put("available",i.getAvailable().getDecimalValue());m.put("lowStock",i.getLowStock());m.put("lotCount",i.getLotCount());return m;}
    private static Map<String,Object>movement(StockMovement m){return Map.of("movementId",m.getMovementId(),"itemId",m.getItemId(),"lotId",m.getLotId(),"warehouseId",m.getWarehouseId(),"type",m.getType().name(),"quantity",m.getQuantity().getDecimalValue(),"unit",m.getQuantity().getUnit());}
    private static Map<String,Object>balance(StockBalance b){return Map.of("itemId",b.getItemId(),"warehouseId",b.getWarehouseId(),"onHand",b.getOnHand().getDecimalValue(),"reserved",b.getReserved().getDecimalValue(),"available",b.getAvailable().getDecimalValue(),"unit",b.getOnHand().getUnit());}
}
