ALTER TABLE ord_order ADD COLUMN IF NOT EXISTS updated_at BIGINT;
ALTER TABLE ord_order ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE ord_order ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);
ALTER TABLE ord_order ADD COLUMN IF NOT EXISTS row_version BIGINT NOT NULL DEFAULT 0;
UPDATE ord_order SET updated_at = created_at WHERE updated_at IS NULL;
ALTER TABLE ord_order ALTER COLUMN updated_at SET NOT NULL;
ALTER TABLE ord_order_line ADD COLUMN IF NOT EXISTS row_version BIGINT NOT NULL DEFAULT 0;
