spring:
  application:
    name: smartfarm-reporting-service
  profiles:
    default: dev
server:
  port: 8085
management:
  endpoints.web.exposure.include: health,info,prometheus
  endpoint.health.probes.enabled: true
spring.grpc.server.port: 9095
smartfarm:
  grpc:
    tls:
      enabled: false
      cert-chain: ${GRPC_CERT_CHAIN:}
      private-key: ${GRPC_PRIVATE_KEY:}
  mqtt:
    url: ${MQTT_URL:tcp://localhost:1883}
