package com.htv.smartfarm.livestock.task;

import java.util.Optional;
import java.util.UUID;

import org.springframework.stereotype.Repository;

import com.htv.smartfarm.livestock.outbox.OutboxEntity;
import com.htv.smartfarm.livestock.outbox.OutboxJpaRepository;

/**
 * Persistence facade for the task aggregate and its outbox row. Backed by Spring
 * Data JPA ({@link TaskJpaRepository} / {@link OutboxJpaRepository}); the schema
 * is generated by Hibernate. The public {@link Task} record and method signatures
 * are unchanged from the former JdbcTemplate implementation so callers are not
 * affected.
 */
@Repository
public class TaskStore {

    public record Task(String id, String tenant, String farm, String title, String assignee, String status,
                       long createdAt) {
    }

    private final TaskJpaRepository tasks;
    private final OutboxJpaRepository outbox;

    public TaskStore(TaskJpaRepository tasks, OutboxJpaRepository outbox) {
        this.tasks = tasks;
        this.outbox = outbox;
    }

    private static Task toTask(TaskEntity e) {
        return new Task(e.getId(), e.getTenantId(), e.getFarmId(), e.getTitle(), e.getAssigneeId(),
                e.getStatus(), e.getCreatedAt());
    }

    public Optional<Task> byIdempotency(String tenant, String key) {
        return tasks.findByTenantIdAndIdempotencyKey(tenant, key).map(TaskStore::toTask);
    }

    public Optional<Task> byId(String tenant, String id) {
        return tasks.findByTenantIdAndId(tenant, id).map(TaskStore::toTask);
    }

    public void insert(Task task, String key) {
        tasks.save(new TaskEntity(task.id(), task.tenant(), task.farm(), task.title(), task.assignee(),
                task.status(), task.createdAt(), key));
    }

    public void insertOutbox(Task task, String correlation) {
        outbox.save(new OutboxEntity(UUID.randomUUID().toString(), task.tenant(), task.id(),
                "task-created.v1", correlation, task.createdAt(), "NEW"));
    }
}
