package com.htv.smartfarm.livestock.task;

import java.util.Optional;
import java.util.UUID;

import org.springframework.stereotype.Repository;

import com.htv.smartfarm.livestock.outbox.OutboxEntity;
import com.htv.smartfarm.livestock.outbox.OutboxJpaRepository;

/**
 * Persistence facade for the task aggregate and its outbox row. Backed by Spring
 * Data JPA ({@link TaskJpaRepository} / {@link OutboxJpaRepository}); the schema
 * is generated by Hibernate. The public {@link Task} record and method signatures
 * are unchanged from the former JdbcTemplate implementation so callers are not
 * affected.
 */
@Repository
public class TaskStore {

    public record Task(String id, String tenant, String farm, String title, String assignee, String status,
                       long createdAt) {
    }

    private final TaskJpaRepository tasks;
    private final OutboxJpaRepository outbox;

    public TaskStore(TaskJpaRepository tasks, OutboxJpaRepository outbox) {
        this.tasks = tasks;
        this.outbox = outbox;
    }

    private static Task toTask(TaskEntity e) {
        return new Task(e.getId(), e.getTenantId(), e.getFarmId(), e.getTitle(), e.getAssigneeId(),
                e.getStatus(), e.getCreatedAt());
    }

    public Optional<Task> byIdempotency(String tenant, String key) {
        return tasks.findByTenantIdAndIdempotencyKey(tenant, key).map(TaskStore::toTask);
    }

    public Optional<Task> byId(String tenant, String id) {
        return tasks.findByTenantIdAndId(tenant, id).map(TaskStore::toTask);
    }

    public void insert(Task task, String key) {
        tasks.save(new TaskEntity(task.id(), task.tenant(), task.farm(), task.title(), task.assignee(),
                task.status(), task.createdAt(), key));
    }

    public void insertOutbox(Task task, String correlation) {
        outbox.save(new OutboxEntity(UUID.randomUUID().toString(), task.tenant(), task.id(),
                "task-created.v1", correlation, task.createdAt(), "NEW"));
    }

    // ---- lifecycle access (operate directly on the entity) ----

    public java.util.Optional<TaskEntity> entity(String tenant, String id) {
        return tasks.findByTenantIdAndId(tenant, id);
    }

    public TaskEntity save(TaskEntity e) {
        return tasks.save(e);
    }

    public java.util.List<TaskEntity> list(String tenant, String farm, String status, String assignee, int limit) {
        return tasks.list(tenant, farm, status, assignee,
                org.springframework.data.domain.PageRequest.of(0, Math.max(1, Math.min(limit, 200))));
    }

    public java.util.List<TaskEntity> acceptOverdue(long now, int limit) {
        return tasks.acceptOverdue(now, org.springframework.data.domain.PageRequest.of(0, Math.max(1, Math.min(limit, 500))));
    }

    public java.util.List<TaskEntity> reportOverdue(long now, int limit) {
        return tasks.reportOverdue(now, org.springframework.data.domain.PageRequest.of(0, Math.max(1, Math.min(limit, 500))));
    }

    /** Write a lifecycle event to the outbox with a specific event type (e.g. task-assigned.v1). */
    public void insertLifecycleOutbox(String tenant, String taskId, String eventType, String correlation, long at) {
        outbox.save(new OutboxEntity(UUID.randomUUID().toString(), tenant, taskId,
                eventType, correlation, at, "NEW"));
    }
}
