package com.htv.smartfarm.livestock.task;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * JPA mapping of the {@code sf_task} aggregate. Schema is generated by Hibernate
 * ({@code ddl-auto}); there is no hand-maintained schema.sql. The unique
 * constraint on (tenant_id, idempotency_key) enforces idempotent task creation
 * at the database level, matching the original JDBC schema.
 */
@Entity
@Table(name = "sf_task",
        uniqueConstraints = @UniqueConstraint(name = "uq_task_idempotency", columnNames = {"tenant_id", "idempotency_key"}),
        indexes = @Index(name = "ix_task_tenant_farm", columnList = "tenant_id,farm_id"))
public class TaskEntity {

    @Id
    @Column(length = 36)
    private String id;

    @Column(name = "tenant_id", nullable = false, length = 100)
    private String tenantId;

    @Column(name = "farm_id", nullable = false, length = 100)
    private String farmId;

    @Column(nullable = false, length = 200)
    private String title;

    @Column(name = "assignee_id", nullable = false, length = 100)
    private String assigneeId;

    @Column(nullable = false, length = 32)
    private String status;

    @Column(name = "created_at", nullable = false)
    private long createdAt;

    @Column(name = "idempotency_key", nullable = false, length = 128)
    private String idempotencyKey;

    protected TaskEntity() {
        // for JPA
    }

    public TaskEntity(String id, String tenantId, String farmId, String title, String assigneeId,
                      String status, long createdAt, String idempotencyKey) {
        this.id = id;
        this.tenantId = tenantId;
        this.farmId = farmId;
        this.title = title;
        this.assigneeId = assigneeId;
        this.status = status;
        this.createdAt = createdAt;
        this.idempotencyKey = idempotencyKey;
    }

    public String getId() {
        return id;
    }

    public String getTenantId() {
        return tenantId;
    }

    public String getFarmId() {
        return farmId;
    }

    public String getTitle() {
        return title;
    }

    public String getAssigneeId() {
        return assigneeId;
    }

    public String getStatus() {
        return status;
    }

    public long getCreatedAt() {
        return createdAt;
    }

    public String getIdempotencyKey() {
        return idempotencyKey;
    }
}
