package com.htv.smartfarm.health.outbox;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Lob;
import jakarta.persistence.Table;

/** JPA mapping of {@code h_outbox}. Schema generated by Hibernate (ddl-auto). */
@Entity
@Table(name = "h_outbox",
        indexes = @Index(name = "ix_h_outbox_status", columnList = "status"))
public class HealthOutboxEntity {

    @Id
    @Column(name = "event_id", length = 36)
    private String eventId;

    @Column(name = "tenant_id", nullable = false, length = 100)
    private String tenantId;

    @Column(name = "farm_id", nullable = false, length = 100)
    private String farmId;

    @Column(name = "aggregate_id", nullable = false, length = 36)
    private String aggregateId;

    @Column(name = "event_type", nullable = false, length = 80)
    private String eventType;

    @Lob
    @org.hibernate.annotations.JdbcTypeCode(org.hibernate.type.SqlTypes.VARBINARY)
    @Column(nullable = false)
    private byte[] payload;

    @Column(nullable = false, length = 16)
    private String status;

    protected HealthOutboxEntity() {
    }

    public HealthOutboxEntity(String eventId, String tenantId, String farmId, String aggregateId,
                              String eventType, byte[] payload, String status) {
        this.eventId = eventId;
        this.tenantId = tenantId;
        this.farmId = farmId;
        this.aggregateId = aggregateId;
        this.eventType = eventType;
        this.payload = payload;
        this.status = status;
    }

    public String getEventId() {
        return eventId;
    }

    public String getTenantId() {
        return tenantId;
    }

    public String getFarmId() {
        return farmId;
    }

    public String getEventType() {
        return eventType;
    }

    public byte[] getPayload() {
        return payload;
    }

    public String getStatus() {
        return status;
    }

    public void markPublished() {
        this.status = "PUBLISHED";
    }
}
