import { useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { gql } from '../../lib/api'
import { useAuth, hasScope } from '../../lib/auth'
import { Badge, Button, Card, ErrorMsg, Field, Input, PageHeader } from '../../components/ui'
const Q=`query { roles(page:{size:100}){nodes{roleId code name type permissions{code resourceType action description}}} permissions(page:{size:100}){nodes{code resourceType action description}} }`
const CR=`mutation($input:AuthorizationRoleInput!){createAuthorizationRole(input:$input){code name type}}`
const CP=`mutation($input:AuthorizationPermissionInput!){createAuthorizationPermission(input:$input){code resourceType action description}}`
const G=`mutation($r:String!,$p:String!){grantPermissionToAuthorizationRole(roleCode:$r,permissionCode:$p){code permissions{code}}}`
const V=`mutation($r:String!,$p:String!){revokePermissionFromAuthorizationRole(roleCode:$r,permissionCode:$p){code permissions{code}}}`
type P={code:string;resourceType:string;action:string;description?:string}; type R={roleId:string;code:string;name:string;type:string;permissions:P[]}
export default function Authorization(){const {me}=useAuth();const qc=useQueryClient();const canRole=hasScope(me,'identity:role:manage');const canPermission=hasScope(me,'identity:permission:manage');const [role,setRole]=useState('');const [roleName,setRoleName]=useState('');const [code,setCode]=useState('');const [resource,setResource]=useState('');const [action,setAction]=useState('');const [description,setDescription]=useState('');
const q=useQuery({queryKey:['authorizationCatalog'],queryFn:()=>gql<{roles:{nodes:R[]};permissions:{nodes:P[]}}>(Q)});const refresh=()=>qc.invalidateQueries({queryKey:['authorizationCatalog']});
const createRole=useMutation({mutationFn:()=>gql(CR,{input:{code:role,name:roleName}}),onSuccess:refresh});const createPermission=useMutation({mutationFn:()=>gql(CP,{input:{code,resourceType:resource,action,description}}),onSuccess:refresh});const grant=useMutation({mutationFn:(x:{r:string;p:string;revoke:boolean})=>gql(x.revoke?V:G,{r:x.r,p:x.p}),onSuccess:refresh});
function roleSubmit(e:FormEvent){e.preventDefault();createRole.mutate()} function permissionSubmit(e:FormEvent){e.preventDefault();createPermission.mutate()}
return <><PageHeader title="Vai trò và quyền" sub="Permission từ cấu hình được đồng bộ cộng dồn; xóa và thu hồi chỉ thực hiện thủ công."/><ErrorMsg error={q.error||createRole.error||createPermission.error||grant.error}/><div className="grid gap-4 lg:grid-cols-2">{canRole&&<Card title="Tạo vai trò"><form className="space-y-3" onSubmit={roleSubmit}><Field label="Mã vai trò"><Input required value={role} onChange={e=>setRole(e.target.value.toUpperCase())}/></Field><Field label="Tên"><Input required value={roleName} onChange={e=>setRoleName(e.target.value)}/></Field><Button disabled={createRole.isPending}>Tạo vai trò</Button></form></Card>}{canPermission&&<Card title="Tạo permission"><form className="space-y-3" onSubmit={permissionSubmit}><Field label="Code"><Input required value={code} onChange={e=>setCode(e.target.value.toLowerCase())}/></Field><Field label="Resource type"><Input required value={resource} onChange={e=>setResource(e.target.value)}/></Field><Field label="Action"><Input required value={action} onChange={e=>setAction(e.target.value)}/></Field><Field label="Mô tả"><Input value={description} onChange={e=>setDescription(e.target.value)}/></Field><Button disabled={createPermission.isPending}>Tạo permission</Button></form></Card>}</div><div className="mt-4 space-y-4">{q.data?.roles.nodes.map(r=><Card key={r.roleId} title={`${r.name} (${r.code})`} actions={<Badge tone={r.type==='SYSTEM'?'warn':'info'}>{r.type}</Badge>}><div className="grid gap-2 md:grid-cols-2">{q.data!.permissions.nodes.map(p=>{const checked=r.permissions.some(x=>x.code===p.code);return <label key={p.code} className="flex items-center gap-2 rounded border p-2 text-sm"><input type="checkbox" checked={checked} disabled={!canPermission||r.type==='PLATFORM'} onChange={()=>grant.mutate({r:r.code,p:p.code,revoke:checked})}/><span className="font-mono text-xs">{p.code}</span></label>})}</div></Card>)}</div></>}
