package com.htv.smartfarm.inventory.domain.item;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * JPA mapping of {@code inv_item}. Schema generated by Hibernate (ddl-auto).
 */
@Entity
@Table(name = "inv_item",
        uniqueConstraints = @UniqueConstraint(name = "uq_inv_item_sku", columnNames = {"tenant_id", "sku"}))
public class ItemEntity {

    @Id
    @Column(length = 36)
    private String id;

    @Column(name = "tenant_id", nullable = false, length = 100)
    private String tenantId;

    @Column(nullable = false, length = 80)
    private String sku;

    @Column(nullable = false, length = 200)
    private String name;

    @Column(nullable = false, length = 20)
    private String unit;
    @jakarta.persistence.Enumerated(jakarta.persistence.EnumType.STRING)
    @Column(nullable = false, length = 60)
    private ItemCategoryValue category;

    @Column(nullable = false)
    private boolean active = true;

    /**
     * Reorder threshold (decimal string, same unit as the item). "0" = no threshold (never low).
     */
    @Column(name = "reorder_threshold", nullable = false, length = 40)
    private String reorderThreshold = "0";

    protected ItemEntity() {
    }

    public ItemEntity(String id, String tenantId, String sku, String name, String unit, String category) {
        this(id, tenantId, sku, name, unit, category, "0");
    }

    public ItemEntity(String id, String tenantId, String sku, String name, String unit, String category, String reorderThreshold) {
        this.id = required(id, "id");
        this.tenantId = required(tenantId, "tenantId");
        this.sku = required(sku, "sku").toUpperCase();
        this.name = required(name, "name");
        this.unit = required(unit, "unit").toUpperCase();
        this.category = ItemCategoryValue.parse(category);
        this.reorderThreshold = (reorderThreshold == null || reorderThreshold.isBlank()) ? "0" : reorderThreshold;
    }

    private static String required(String value, String field) {
        if (value == null || value.isBlank()) throw new IllegalArgumentException(field + " is required");
        return value.trim();
    }

    public String getId() {
        return id;
    }

    public String getTenantId() {
        return tenantId;
    }

    public String getSku() {
        return sku;
    }

    public String getName() {
        return name;
    }

    public String getUnit() {
        return unit;
    }

    public ItemCategoryValue getCategory() {
        return category;
    }

    public String getReorderThreshold() {
        return reorderThreshold;
    }

    public void update(String name,String unit,String category,String threshold) {
        this.name=required(name,"name"); this.unit=required(unit,"unit").toUpperCase();
        this.category=ItemCategoryValue.parse(category);
        if(threshold!=null&&!threshold.isBlank()) new java.math.BigDecimal(threshold);
        this.reorderThreshold=threshold==null||threshold.isBlank()?"0":threshold.trim();
    }
    public void setActive(boolean active){this.active=active;}
    public boolean isActive(){return active;}
}
