package com.htv.smartfarm.livestock.animal;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * JPA mapping of the {@code sf_animal} aggregate. A tag code is unique within a tenant+farm
 * (an ear-tag identifies exactly one animal on a farm), which also gives idempotent
 * registration at the database level. Schema is generated by Hibernate ({@code ddl-auto}).
 */
@Entity
@Table(name = "sf_animal",
        uniqueConstraints = @UniqueConstraint(name = "uq_animal_tag", columnNames = {"tenant_id", "farm_id", "tag_code"}),
        indexes = @Index(name = "ix_animal_farm_batch", columnList = "tenant_id,farm_id,batch_id"))
public class AnimalEntity {

    @Id
    @Column(name = "animal_id", length = 36)
    private String id;

    @Column(name = "tenant_id", nullable = false, length = 100)
    private String tenantId;

    @Column(name = "farm_id", nullable = false, length = 100)
    private String farmId;

    @Column(name = "barn_id", length = 100)
    private String barnId;

    @Column(name = "batch_id", length = 100)
    private String batchId;

    @Column(name = "tag_code", nullable = false, length = 100)
    private String tagCode;

    @Column(name = "species", length = 80)
    private String species;

    @Column(name = "birth_date")
    private Long birthDate; // epoch millis, nullable

    /** AnimalStatus enum name, e.g. ANIMAL_STATUS_ACTIVE. */
    @Column(name = "status", nullable = false, length = 40)
    private String status;

    @Column(name = "created_at", nullable = false)
    private long createdAt;

    protected AnimalEntity() {
    }

    public AnimalEntity(String id, String tenantId, String farmId, String barnId, String batchId, String tagCode,
                        String species, Long birthDate, String status, long createdAt) {
        this.id = id;
        this.tenantId = tenantId;
        this.farmId = farmId;
        this.barnId = barnId;
        this.batchId = batchId;
        this.tagCode = tagCode;
        this.species = species;
        this.birthDate = birthDate;
        this.status = status;
        this.createdAt = createdAt;
    }

    public String getId() { return id; }
    public String getTenantId() { return tenantId; }
    public String getFarmId() { return farmId; }
    public String getBarnId() { return barnId; }
    public String getBatchId() { return batchId; }
    public String getTagCode() { return tagCode; }
    public String getSpecies() { return species; }
    public Long getBirthDate() { return birthDate; }
    public String getStatus() { return status; }
    public long getCreatedAt() { return createdAt; }

    public void setStatus(String status) { this.status = status; }
    public void setBarnId(String barnId) { this.barnId = barnId; }
    public void setBatchId(String batchId) { this.batchId = batchId; }
}
