package com.htv.smartfarm.identity.user;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/** JPA mapping of {@code sf_role}. Schema generated by Hibernate (ddl-auto). */
@Entity
@Table(name = "sf_role")
public class RoleEntity {

    @Id
    @Column(length = 40)
    private String code;

    protected RoleEntity() {
    }

    public RoleEntity(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
