package com.htv.smartfarm.identity.user;

import java.io.Serializable;
import java.util.Objects;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;

/** JPA mapping of {@code sf_role_permission}. Schema generated by Hibernate (ddl-auto). */
@Entity
@Table(name = "sf_role_permission")
@IdClass(RolePermissionEntity.Key.class)
public class RolePermissionEntity {

    @Id
    @Column(name = "role_code", length = 40)
    private String roleCode;

    @Id
    @Column(name = "permission_code", length = 80)
    private String permissionCode;

    protected RolePermissionEntity() {
    }

    public RolePermissionEntity(String roleCode, String permissionCode) {
        this.roleCode = roleCode;
        this.permissionCode = permissionCode;
    }

    public static class Key implements Serializable {
        private String roleCode;
        private String permissionCode;

        public Key() {
        }

        public Key(String roleCode, String permissionCode) {
            this.roleCode = roleCode;
            this.permissionCode = permissionCode;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (!(o instanceof Key k)) return false;
            return Objects.equals(roleCode, k.roleCode) && Objects.equals(permissionCode, k.permissionCode);
        }

        @Override
        public int hashCode() {
            return Objects.hash(roleCode, permissionCode);
        }
    }
}
