package com.htv.smartfarm.identity.user;

import java.io.Serializable;
import java.util.Objects;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;

/** JPA mapping of {@code sf_user_role}. Schema generated by Hibernate (ddl-auto). */
@Entity
@Table(name = "sf_user_role")
@IdClass(UserRoleEntity.Key.class)
public class UserRoleEntity {

    @Id
    @Column(name = "user_id", length = 36)
    private String userId;

    @Id
    @Column(name = "role_code", length = 40)
    private String roleCode;

    protected UserRoleEntity() {
    }

    public UserRoleEntity(String userId, String roleCode) {
        this.userId = userId;
        this.roleCode = roleCode;
    }

    public static class Key implements Serializable {
        private String userId;
        private String roleCode;

        public Key() {
        }

        public Key(String userId, String roleCode) {
            this.userId = userId;
            this.roleCode = roleCode;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (!(o instanceof Key k)) return false;
            return Objects.equals(userId, k.userId) && Objects.equals(roleCode, k.roleCode);
        }

        @Override
        public int hashCode() {
            return Objects.hash(userId, roleCode);
        }
    }
}
