package com.htv.smartfarm.identity.user;

import java.util.Optional;
import java.util.Set;
import java.util.TreeSet;
import java.util.UUID;

import org.springframework.stereotype.Repository;


/**
 * Identity persistence facade. Backed by Spring Data JPA; schema is generated by
 * Hibernate and seed roles/permissions are inserted by {@link RoleSeeder}. Public
 * {@link User} record and method signatures are unchanged from the former
 * JdbcTemplate implementation so callers (AuthService, AdminController) are
 * unaffected.
 */
@Repository
public class UserRepository {

    public record User(String id, String tenantId, String email, String passwordHash, boolean enabled,
                       int failedAttempts, Long lockedUntil) {
    }

    private final UserJpaRepository users;
    private final RoleJpaRepository roles;
    private final RolePermissionJpaRepository rolePermissions;
    private final UserRoleJpaRepository userRoles;

    public UserRepository(UserJpaRepository users, RoleJpaRepository roles,
                          RolePermissionJpaRepository rolePermissions, UserRoleJpaRepository userRoles) {
        this.users = users;
        this.roles = roles;
        this.rolePermissions = rolePermissions;
        this.userRoles = userRoles;
    }

    private static User toUser(UserEntity e) {
        return new User(e.getId(), e.getTenantId(), e.getEmail(), e.getPasswordHash(), e.isEnabled(),
                e.getFailedAttempts(), e.getLockedUntil());
    }

    public Optional<User> findByEmail(String tenant, String email) {
        return users.findByTenantIdAndEmail(tenant, email).map(UserRepository::toUser);
    }

    public Optional<User> findById(String id) {
        return users.findById(id).map(UserRepository::toUser);
    }

    public User create(String tenant, String email, String hash) {
        String id = UUID.randomUUID().toString();
        users.save(new UserEntity(id, tenant, email, hash, true, 0, null));
        return findById(id).orElseThrow();
    }

    public void failed(User user, int attempts, Long lockedUntil) {
        users.findById(user.id()).ifPresent(e -> {
            e.setFailedAttempts(attempts);
            e.setLockedUntil(lockedUntil);
            users.save(e);
        });
    }

    public void resetFailures(String id) {
        users.findById(id).ifPresent(e -> {
            e.setFailedAttempts(0);
            e.setLockedUntil(null);
            users.save(e);
        });
    }

    public void setEnabled(String id, boolean enabled) {
        users.findById(id).ifPresent(e -> {
            e.setEnabled(enabled);
            users.save(e);
        });
    }

    public void setPassword(String id, String hash) {
        users.findById(id).ifPresent(e -> {
            e.setPasswordHash(hash);
            users.save(e);
        });
    }

    public void assignRole(String userId, String role) {
        userRoles.save(new UserRoleEntity(userId, role));
    }

    public void removeRole(String userId, String role) {
        userRoles.deleteById(new UserRoleEntity.Key(userId, role));
    }

    public Set<String> roles(String id) {
        return new TreeSet<>(users.findRoleCodes(id));
    }

    public Set<String> scopes(String id) {
        Set<String> granted = new TreeSet<>(users.findScopes(id));
        // Super-admin: the wildcard "*" expands to every permission the system knows, plus the
        // wildcard itself (kept so the gRPC layer recognises super-admin for scopes added later).
        if (granted.contains("*")) {
            granted.addAll(users.findAllPermissions());
        }
        return granted;
    }

    public boolean roleExists(String code) {
        return roles.existsById(code);
    }

    /** All defined roles, sorted. */
    public java.util.List<String> allRoles() {
        return users.findAllRoles();
    }

    /** Permissions granted to a role, sorted (includes the wildcard "*" if present). */
    public java.util.List<String> permissionsOf(String role) {
        return users.findPermissionsByRole(role);
    }

    /** Every concrete permission known to the system (wildcard excluded), sorted. */
    public java.util.List<String> allPermissions() {
        return users.findAllPermissions();
    }

    public void createRole(String code) {
        roles.save(new RoleEntity(code));
    }

    public void grantPermission(String role, String permission) {
        rolePermissions.save(new RolePermissionEntity(role, permission));
    }
}
