package com.htv.smartfarm.identity.token;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.HexFormat;
import java.util.Optional;

import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/**
 * Refresh-token persistence facade. Backed by Spring Data JPA; schema generated by
 * Hibernate. Public {@link Session} record and method signatures (and the SHA-256
 * token digest) are unchanged from the former JdbcTemplate implementation.
 */
@Repository
public class RefreshRepository {

    public record Session(String id, String userId, String familyId, long expiresAt, boolean revoked) {
    }

    private final RefreshJpaRepository refresh;

    public RefreshRepository(RefreshJpaRepository refresh) {
        this.refresh = refresh;
    }

    public static String digest(String raw) {
        try {
            byte[] bytes = MessageDigest.getInstance("SHA-256").digest(raw.getBytes(StandardCharsets.UTF_8));
            return HexFormat.of().formatHex(bytes);
        } catch (Exception ex) {
            throw new IllegalStateException(ex);
        }
    }

    public void insert(String id, String userId, String family, String raw, long expiry) {
        refresh.save(new RefreshEntity(id, userId, family, digest(raw), expiry, false));
    }

    public Optional<Session> find(String raw) {
        return refresh.findByTokenHash(digest(raw))
                .map(e -> new Session(e.getId(), e.getUserId(), e.getFamilyId(), e.getExpiresAt(), e.isRevoked()));
    }

    /** Consume (revoke) a refresh row if it is still active. Returns true iff a NEW->revoked transition happened. */
    @Transactional
    public boolean consume(String id) {
        return refresh.findById(id)
                .filter(e -> !e.isRevoked())
                .map(e -> {
                    e.setRevoked(true);
                    return true;
                })
                .orElse(false);
    }

    @Transactional
    public void revokeFamily(String family) {
        refresh.revokeFamily(family);
    }

    @Transactional
    public void revokeUser(String user) {
        refresh.revokeUser(user);
    }
}
