package com.htv.smartfarm.identity.token;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;

/** JPA mapping of {@code sf_refresh}. Schema generated by Hibernate (ddl-auto). */
@Entity
@Table(name = "sf_refresh",
        indexes = {
                @Index(name = "ix_refresh_family", columnList = "family_id"),
                @Index(name = "ix_refresh_user", columnList = "user_id")
        })
public class RefreshEntity {

    @Id
    @Column(length = 36)
    private String id;

    @Column(name = "user_id", nullable = false, length = 36)
    private String userId;

    @Column(name = "family_id", nullable = false, length = 36)
    private String familyId;

    @Column(name = "token_hash", nullable = false, unique = true, length = 64)
    private String tokenHash;

    @Column(name = "expires_at", nullable = false)
    private long expiresAt;

    @Column(nullable = false)
    private boolean revoked;

    protected RefreshEntity() {
    }

    public RefreshEntity(String id, String userId, String familyId, String tokenHash, long expiresAt, boolean revoked) {
        this.id = id;
        this.userId = userId;
        this.familyId = familyId;
        this.tokenHash = tokenHash;
        this.expiresAt = expiresAt;
        this.revoked = revoked;
    }

    public String getId() {
        return id;
    }

    public String getUserId() {
        return userId;
    }

    public String getFamilyId() {
        return familyId;
    }

    public long getExpiresAt() {
        return expiresAt;
    }

    public boolean isRevoked() {
        return revoked;
    }

    public void setRevoked(boolean revoked) {
        this.revoked = revoked;
    }
}
