package com.htv.smartfarm.reporting.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * JPA mapping of {@code rpt_export_job}. An export request creates a QUEUED row; a background
 * worker picks it up (RUNNING), produces the artifact, then marks COMPLETED with a file path
 * (or FAILED with an error code). Idempotent on {@code (tenant_id, idempotency_key)} so a
 * retried RequestExport returns the existing job instead of queueing a duplicate.
 * Schema generated by Hibernate ({@code ddl-auto}).
 */
@Entity
@Table(name = "rpt_export_job",
        uniqueConstraints = @UniqueConstraint(name = "uq_rpt_idem", columnNames = {"tenant_id", "idempotency_key"}),
        indexes = @Index(name = "ix_rpt_status", columnList = "status,created_at"))
public class ExportJobEntity {

    @Id
    @Column(name = "job_id", length = 36)
    private String id;

    @Column(name = "tenant_id", nullable = false, length = 100)
    private String tenantId;

    @Column(name = "farm_id", nullable = false, length = 100)
    private String farmId;

    /** ReportType enum name, e.g. REPORT_TYPE_INVENTORY. */
    @Column(name = "report_type", nullable = false, length = 40)
    private String reportType;

    /** ReportFormat enum name, e.g. REPORT_FORMAT_CSV. */
    @Column(name = "report_format", nullable = false, length = 40)
    private String reportFormat;

    /** ExportStatus enum name: QUEUED / RUNNING / COMPLETED / FAILED / EXPIRED. */
    @Column(name = "status", nullable = false, length = 40)
    private String status;

    @Column(name = "period_from")
    private Long periodFrom;

    @Column(name = "period_to")
    private Long periodTo;

    @Column(name = "template_id", length = 100)
    private String templateId;

    @Column(name = "file_path", length = 500)
    private String filePath;

    @Column(name = "content_type", length = 100)
    private String contentType;

    @Column(name = "error_code", length = 100)
    private String errorCode;

    @Column(name = "created_at", nullable = false)
    private long createdAt;

    @Column(name = "completed_at")
    private Long completedAt;

    @Column(name = "idempotency_key", nullable = false, length = 128)
    private String idempotencyKey;

    protected ExportJobEntity() {
    }

    public ExportJobEntity(String id, String tenantId, String farmId, String reportType, String reportFormat,
                           String status, Long periodFrom, Long periodTo, String templateId, long createdAt,
                           String idempotencyKey) {
        this.id = id;
        this.tenantId = tenantId;
        this.farmId = farmId;
        this.reportType = reportType;
        this.reportFormat = reportFormat;
        this.status = status;
        this.periodFrom = periodFrom;
        this.periodTo = periodTo;
        this.templateId = templateId;
        this.createdAt = createdAt;
        this.idempotencyKey = idempotencyKey;
    }

    public String getId() { return id; }
    public String getTenantId() { return tenantId; }
    public String getFarmId() { return farmId; }
    public String getReportType() { return reportType; }
    public String getReportFormat() { return reportFormat; }
    public String getStatus() { return status; }
    public Long getPeriodFrom() { return periodFrom; }
    public Long getPeriodTo() { return periodTo; }
    public String getTemplateId() { return templateId; }
    public String getFilePath() { return filePath; }
    public String getContentType() { return contentType; }
    public String getErrorCode() { return errorCode; }
    public long getCreatedAt() { return createdAt; }
    public Long getCompletedAt() { return completedAt; }
    public String getIdempotencyKey() { return idempotencyKey; }

    public void markRunning() {
        this.status = "EXPORT_STATUS_RUNNING";
    }

    public void markCompleted(String filePath, String contentType, long at) {
        this.filePath = filePath;
        this.contentType = contentType;
        this.completedAt = at;
        this.status = "EXPORT_STATUS_COMPLETED";
    }

    public void markFailed(String errorCode, long at) {
        this.errorCode = errorCode;
        this.completedAt = at;
        this.status = "EXPORT_STATUS_FAILED";
    }
}
