package com.htv.smartfarm.livestock.outbox;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;

/**
 * JPA mapping of the {@code sf_outbox} table (transactional outbox). A row is
 * written in the SAME transaction as its aggregate change, then relayed to MQTT
 * and flipped NEW -> PUBLISHED. Schema is generated by Hibernate ({@code ddl-auto}).
 */
@Entity
@Table(name = "sf_outbox",
        indexes = @Index(name = "ix_outbox_status", columnList = "status,created_at"))
public class OutboxEntity {

    @Id
    @Column(name = "event_id", length = 36)
    private String eventId;

    @Column(name = "tenant_id", nullable = false, length = 100)
    private String tenantId;

    @Column(name = "aggregate_id", nullable = false, length = 36)
    private String aggregateId;

    @Column(name = "event_type", nullable = false, length = 80)
    private String eventType;

    @Column(name = "correlation_id", length = 128)
    private String correlationId;

    @Column(name = "created_at", nullable = false)
    private long createdAt;

    @Column(nullable = false, length = 16)
    private String status;

    protected OutboxEntity() {
        // for JPA
    }

    public OutboxEntity(String eventId, String tenantId, String aggregateId, String eventType,
                        String correlationId, long createdAt, String status) {
        this.eventId = eventId;
        this.tenantId = tenantId;
        this.aggregateId = aggregateId;
        this.eventType = eventType;
        this.correlationId = correlationId;
        this.createdAt = createdAt;
        this.status = status;
    }

    public String getEventId() {
        return eventId;
    }

    public String getTenantId() {
        return tenantId;
    }

    public String getAggregateId() {
        return aggregateId;
    }

    public String getEventType() {
        return eventType;
    }

    public String getCorrelationId() {
        return correlationId;
    }

    public long getCreatedAt() {
        return createdAt;
    }

    public String getStatus() {
        return status;
    }

    public void markPublished() {
        this.status = "PUBLISHED";
    }
}
