package com.htv.smartfarm.inventory.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/** JPA mapping of {@code inv_inbox} (consumer dedup). Schema generated by Hibernate. */
@Entity
@Table(name = "inv_inbox")
public class InboxEntity {

    @Id
    @Column(name = "event_id", length = 100)
    private String eventId;

    @Column(name = "tenant_id", nullable = false, length = 100)
    private String tenantId;

    @Column(name = "task_id", nullable = false, length = 100)
    private String taskId;

    @Column(name = "received_at", nullable = false)
    private long receivedAt;

    protected InboxEntity() {
    }

    public InboxEntity(String eventId, String tenantId, String taskId, long receivedAt) {
        this.eventId = eventId;
        this.tenantId = tenantId;
        this.taskId = taskId;
        this.receivedAt = receivedAt;
    }
}
