package com.htv.smartfarm.inventory.domain;

import java.math.BigDecimal;

import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/**
 * Inventory persistence facade. Backed by Spring Data JPA; schema is generated by
 * Hibernate. Public records ({@link Item}/{@link Lot}/{@link Movement}) and method
 * signatures are unchanged from the former JdbcTemplate implementation so
 * {@code InventoryCommands} and other callers are unaffected. The atomic
 * increment/decrement semantics (row count == 1) are preserved.
 */
@Repository
public class InventoryRepository {

    public record Item(String id, String tenant, String sku, String name, String unit, String category) {
    }

    public record Lot(String id, String tenant, String itemId, String farmId, String warehouseId) {
    }

    public record Movement(String id, String tenant, String lotId, String kind, BigDecimal quantity,
                           String referenceId) {
    }

    private final ItemJpaRepository items;
    private final LotJpaRepository lots;
    private final BalanceJpaRepository balances;
    private final MovementJpaRepository movements;
    private final InboxJpaRepository inbox;

    public InventoryRepository(ItemJpaRepository items, LotJpaRepository lots, BalanceJpaRepository balances,
                               MovementJpaRepository movements, InboxJpaRepository inbox) {
        this.items = items;
        this.lots = lots;
        this.balances = balances;
        this.movements = movements;
        this.inbox = inbox;
    }

    private static Item toItem(ItemEntity e) {
        return new Item(e.getId(), e.getTenantId(), e.getSku(), e.getName(), e.getUnit(), e.getCategory());
    }

    private static Lot toLot(LotEntity e) {
        return new Lot(e.getId(), e.getTenantId(), e.getItemId(), e.getFarmId(), e.getWarehouseId());
    }

    private static Movement toMovement(MovementEntity e) {
        return new Movement(e.getId(), e.getTenantId(), e.getLotId(), e.getKind(), e.getQuantity(), e.getReferenceId());
    }

    public Item item(String tenant, String id) {
        return items.findByTenantIdAndId(tenant, id).map(InventoryRepository::toItem).orElse(null);
    }

    public Item itemBySku(String tenant, String sku) {
        return items.findByTenantIdAndSku(tenant, sku).map(InventoryRepository::toItem).orElse(null);
    }

    public void createItem(Item i) {
        items.save(new ItemEntity(i.id(), i.tenant(), i.sku(), i.name(), i.unit(), i.category()));
    }

    public Lot lot(String tenant, String id) {
        return lots.findByTenantIdAndId(tenant, id).map(InventoryRepository::toLot).orElse(null);
    }

    public void createLot(Lot l) {
        lots.save(new LotEntity(l.id(), l.tenant(), l.itemId(), l.farmId(), l.warehouseId()));
    }

    public Movement movement(String tenant, String key) {
        return movements.findByTenantIdAndIdempotencyKey(tenant, key).map(InventoryRepository::toMovement).orElse(null);
    }

    public void addMovement(Movement m, String key) {
        movements.save(new MovementEntity(m.id(), m.tenant(), m.lotId(), m.kind(), m.quantity(), m.referenceId(), key));
    }

    public void createBalance(String tenant, String lot) {
        balances.save(new BalanceEntity(tenant, lot, BigDecimal.ZERO));
    }

    @Transactional
    public boolean increment(String tenant, String lot, BigDecimal delta) {
        return balances.increment(tenant, lot, delta) == 1;
    }

    @Transactional
    public boolean decrement(String tenant, String lot, BigDecimal delta) {
        return balances.decrement(tenant, lot, delta) == 1;
    }

    public BigDecimal balance(String tenant, String item, String warehouse) {
        BigDecimal n = balances.sumBalance(tenant, item, warehouse);
        return n == null ? BigDecimal.ZERO : n;
    }

    public boolean inboxExists(String id) {
        return inbox.existsById(id);
    }

    public boolean recordInbox(String id, String tenant, String taskId) {
        if (inbox.existsById(id)) {
            return false;
        }
        inbox.save(new InboxEntity(id, tenant, taskId, System.currentTimeMillis()));
        return true;
    }

    public long inboxCount() {
        return inbox.count();
    }
}
