package com.htv.smartfarm.inventory.domain;

import com.htv.smartfarm.inventory.domain.item.ItemEntity;
import com.htv.smartfarm.inventory.domain.item.ItemJpaRepository;
import com.htv.smartfarm.inventory.domain.lot.LotEntity;
import com.htv.smartfarm.inventory.domain.lot.LotJpaRepository;
import com.htv.smartfarm.inventory.domain.stock.BalanceEntity;
import com.htv.smartfarm.inventory.domain.stock.BalanceId;
import com.htv.smartfarm.inventory.domain.stock.BalanceJpaRepository;
import com.htv.smartfarm.inventory.domain.movement.MovementEntity;
import com.htv.smartfarm.inventory.domain.movement.MovementJpaRepository;
import com.htv.smartfarm.inventory.domain.reservation.ReservationEntity;
import com.htv.smartfarm.inventory.domain.reservation.ReservationJpaRepository;
import com.htv.smartfarm.inventory.domain.inbox.InboxEntity;
import com.htv.smartfarm.inventory.domain.inbox.InboxJpaRepository;

import java.math.BigDecimal;

import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/**
 * Inventory persistence facade. Backed by Spring Data JPA; schema is generated by
 * Hibernate. Public records ({@link Item}/{@link Lot}/{@link Movement}) and method
 * signatures are unchanged from the former JdbcTemplate implementation so
 * {@code InventoryCommands} and other callers are unaffected. The atomic
 * increment/decrement semantics (row count == 1) are preserved.
 */
@Repository
public class InventoryRepository {

    public record Item(String id, String tenant, String sku, String name, String unit, String category,
                       String reorderThreshold) {
    }

    /**
     * Row for low-stock listing: aggregated balance for an (item, warehouse) under a farm.
     */
    public record LowBalance(String itemId, String warehouseId, String unit, BigDecimal onHand, BigDecimal reserved,
                             BigDecimal reorderThreshold) {
    }

    public record Lot(String id, String tenant, String itemId, String farmId, String warehouseId) {
    }

    public record Movement(String id, String tenant, String lotId, String kind, BigDecimal quantity,
                           String referenceId) {
    }

    public record Reservation(String id, String tenant, String orderId, String itemId, String lotId,
                              String warehouseId, BigDecimal quantity, String status) {
    }

    private final ItemJpaRepository items;
    private final LotJpaRepository lots;
    private final BalanceJpaRepository balances;
    private final MovementJpaRepository movements;
    private final InboxJpaRepository inbox;
    private final ReservationJpaRepository reservations;

    public InventoryRepository(ItemJpaRepository items, LotJpaRepository lots, BalanceJpaRepository balances,
                               MovementJpaRepository movements, InboxJpaRepository inbox,
                               ReservationJpaRepository reservations) {
        this.items = items;
        this.lots = lots;
        this.balances = balances;
        this.movements = movements;
        this.inbox = inbox;
        this.reservations = reservations;
    }

    private static Item toItem(ItemEntity e) {
        return new Item(e.getId(), e.getTenantId(), e.getSku(), e.getName(), e.getUnit(), e.getCategory().name(), e.getReorderThreshold());
    }

    private static Lot toLot(LotEntity e) {
        return new Lot(e.getId(), e.getTenantId(), e.getItemId(), e.getFarmId(), e.getWarehouseId());
    }

    private static Movement toMovement(MovementEntity e) {
        return new Movement(e.getId(), e.getTenantId(), e.getLotId(), e.getKind().name(), e.getQuantity(), e.getReferenceId());
    }

    public Item item(String tenant, String id) {
        return items.findByTenantIdAndId(tenant, id).map(InventoryRepository::toItem).orElse(null);
    }

    public Item itemBySku(String tenant, String sku) {
        return items.findByTenantIdAndSku(tenant, sku).map(InventoryRepository::toItem).orElse(null);
    }

    public void createItem(Item i) {
        items.save(new ItemEntity(i.id(), i.tenant(), i.sku(), i.name(), i.unit(), i.category(), i.reorderThreshold()));
    }

    /**
     * Low-stock rows for a farm: (item, warehouse) whose available (on_hand - reserved) is below the item's reorder threshold (threshold > 0).
     */
    public java.util.List<LowBalance> lowStock(String tenant, String farmId, int limit) {
        var rows = balances.balancesByFarm(tenant, farmId);
        var out = new java.util.ArrayList<LowBalance>();
        for (Object[] r : rows) {
            var threshold = new BigDecimal((String) r[5]);
            if (threshold.signum() <= 0) continue;                 // no threshold set -> never "low"
            var onHand = (BigDecimal) r[3];
            var reserved = (BigDecimal) r[4];
            if (onHand.subtract(reserved).compareTo(threshold) >= 0) continue;   // not below threshold
            out.add(new LowBalance((String) r[0], (String) r[1], (String) r[2], onHand, reserved, threshold));
            if (out.size() >= Math.max(1, limit)) break;
        }
        return out;
    }

    public Lot lot(String tenant, String id) {
        return lots.findByTenantIdAndId(tenant, id).map(InventoryRepository::toLot).orElse(null);
    }

    public void createLot(Lot l) {
        lots.save(new LotEntity(l.id(), l.tenant(), l.itemId(), l.farmId(), l.warehouseId()));
    }

    public Movement movement(String tenant, String key) {
        return movements.findByTenantIdAndIdempotencyKey(tenant, key).map(InventoryRepository::toMovement).orElse(null);
    }

    public void addMovement(Movement m, String key) {
        movements.save(new MovementEntity(m.id(), m.tenant(), m.lotId(), m.kind(), m.quantity(), m.referenceId(), key));
    }

    public void createBalance(String tenant, String lot) {
        balances.save(new BalanceEntity(tenant, lot, BigDecimal.ZERO));
    }

    @Transactional
    public boolean increment(String tenant, String lot, BigDecimal delta) {
        return balances.increment(tenant, lot, delta) == 1;
    }

    @Transactional
    public boolean decrement(String tenant, String lot, BigDecimal delta) {
        return balances.decrement(tenant, lot, delta) == 1;
    }

    public BigDecimal balance(String tenant, String item, String warehouse) {
        BigDecimal n = balances.sumBalance(tenant, item, warehouse);
        return n == null ? BigDecimal.ZERO : n;
    }

    public boolean inboxExists(String id) {
        return inbox.existsById(id);
    }

    public boolean recordInbox(String id, String tenant, String taskId) {
        if (inbox.existsById(id)) {
            return false;
        }
        inbox.save(new InboxEntity(id, tenant, taskId, System.currentTimeMillis()));
        return true;
    }

    public long inboxCount() {
        return inbox.count();
    }

    // ---- Reservations (saga stock holds) ------------------------------------

    private static Reservation toReservation(ReservationEntity e) {
        return new Reservation(e.getId(), e.getTenantId(), e.getOrderId(), e.getItemId(), e.getLotId(),
                e.getWarehouseId(), e.getQuantity(), e.getStatus().name());
    }

    public Reservation reservation(String tenant, String id) {
        return reservations.findByTenantIdAndId(tenant, id).map(InventoryRepository::toReservation).orElse(null);
    }

    public Reservation reservationByKey(String tenant, String key) {
        return reservations.findByTenantIdAndIdempotencyKey(tenant, key).map(InventoryRepository::toReservation).orElse(null);
    }

    public java.util.List<String> lotsWithAvailable(String tenant, String item, String warehouse) {
        return balances.lotsWithAvailable(tenant, item, warehouse);
    }

    /**
     * Atomically hold {@code delta} on a lot; false when available stock is insufficient.
     */
    @Transactional
    public boolean reserveOnLot(String tenant, String lot, BigDecimal delta) {
        return balances.reserve(tenant, lot, delta) == 1;
    }

    @Transactional
    public boolean releaseOnLot(String tenant, String lot, BigDecimal delta) {
        return balances.release(tenant, lot, delta) == 1;
    }

    @Transactional
    public boolean commitOnLot(String tenant, String lot, BigDecimal delta) {
        return balances.commit(tenant, lot, delta) == 1;
    }

    public void saveReservation(Reservation r, String key) {
        reservations.save(new ReservationEntity(r.id(), r.tenant(), r.orderId(), r.itemId(), r.lotId(),
                r.warehouseId(), r.quantity(), r.status(), key));
    }

    @Transactional
    public void markReservationReleased(String tenant, String id) {
        reservations.findByTenantIdAndId(tenant, id).ifPresent(e -> {
            e.markReleased();
            reservations.save(e);
        });
    }

    @Transactional
    public void markReservationCommitted(String tenant, String id) {
        reservations.findByTenantIdAndId(tenant, id).ifPresent(e -> {
            e.markCommitted();
            reservations.save(e);
        });
    }

    public BigDecimal reservedTotal(String tenant, String item, String warehouse) {
        BigDecimal n = balances.sumReserved(tenant, item, warehouse);
        return n == null ? BigDecimal.ZERO : n;
    }
}
