package com.htv.smartfarm.inventory.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/** JPA mapping of {@code inv_item}. Schema generated by Hibernate (ddl-auto). */
@Entity
@Table(name = "inv_item",
        uniqueConstraints = @UniqueConstraint(name = "uq_inv_item_sku", columnNames = {"tenant_id", "sku"}))
public class ItemEntity {

    @Id
    @Column(length = 36)
    private String id;

    @Column(name = "tenant_id", nullable = false, length = 100)
    private String tenantId;

    @Column(nullable = false, length = 80)
    private String sku;

    @Column(nullable = false, length = 200)
    private String name;

    @Column(nullable = false, length = 20)
    private String unit;

    @Column(nullable = false, length = 60)
    private String category;

    /** Reorder threshold (decimal string, same unit as the item). "0" = no threshold (never low). */
    @Column(name = "reorder_threshold", nullable = false, length = 40)
    private String reorderThreshold = "0";

    protected ItemEntity() {
    }

    public ItemEntity(String id, String tenantId, String sku, String name, String unit, String category) {
        this(id, tenantId, sku, name, unit, category, "0");
    }

    public ItemEntity(String id, String tenantId, String sku, String name, String unit, String category, String reorderThreshold) {
        this.id = id;
        this.tenantId = tenantId;
        this.sku = sku;
        this.name = name;
        this.unit = unit;
        this.category = category;
        this.reorderThreshold = (reorderThreshold == null || reorderThreshold.isBlank()) ? "0" : reorderThreshold;
    }

    public String getId() {
        return id;
    }

    public String getTenantId() {
        return tenantId;
    }

    public String getSku() {
        return sku;
    }

    public String getName() {
        return name;
    }

    public String getUnit() {
        return unit;
    }

    public String getCategory() {
        return category;
    }

    public String getReorderThreshold() {
        return reorderThreshold;
    }
}
