package com.htv.smartfarm.inventory.domain;

import java.math.BigDecimal;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/** JPA mapping of {@code inv_movement}. Schema generated by Hibernate (ddl-auto). */
@Entity
@Table(name = "inv_movement",
        uniqueConstraints = @UniqueConstraint(name = "uq_inv_mov_idem", columnNames = {"tenant_id", "idempotency_key"}))
public class MovementEntity {

    @Id
    @Column(length = 36)
    private String id;

    @Column(name = "tenant_id", nullable = false, length = 100)
    private String tenantId;

    @Column(name = "lot_id", nullable = false, length = 36)
    private String lotId;

    @Column(nullable = false, length = 16)
    private String kind;

    @Column(nullable = false, precision = 18, scale = 3)
    private BigDecimal quantity;

    @Column(name = "reference_id", nullable = false, length = 128)
    private String referenceId;

    @Column(name = "idempotency_key", nullable = false, length = 128)
    private String idempotencyKey;

    protected MovementEntity() {
    }

    public MovementEntity(String id, String tenantId, String lotId, String kind, BigDecimal quantity,
                          String referenceId, String idempotencyKey) {
        this.id = id;
        this.tenantId = tenantId;
        this.lotId = lotId;
        this.kind = kind;
        this.quantity = quantity;
        this.referenceId = referenceId;
        this.idempotencyKey = idempotencyKey;
    }

    public String getId() {
        return id;
    }

    public String getTenantId() {
        return tenantId;
    }

    public String getLotId() {
        return lotId;
    }

    public String getKind() {
        return kind;
    }

    public BigDecimal getQuantity() {
        return quantity;
    }

    public String getReferenceId() {
        return referenceId;
    }
}
