package com.htv.smartfarm.inventory.domain.lot;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * JPA mapping of {@code inv_lot}. Schema generated by Hibernate (ddl-auto).
 */
@Entity
@Table(name = "inv_lot")
public class LotEntity {

    @Id
    @Column(length = 36)
    private String id;

    @Column(name = "tenant_id", nullable = false, length = 100)
    private String tenantId;

    @Column(name = "item_id", nullable = false, length = 36)
    private String itemId;

    @Column(name = "farm_id", nullable = false, length = 100)
    private String farmId;

    @Column(name = "warehouse_id", nullable = false, length = 100)
    private String warehouseId;

    protected LotEntity() {
    }

    public LotEntity(String id, String tenantId, String itemId, String farmId, String warehouseId) {
        this.id = id;
        this.tenantId = tenantId;
        this.itemId = itemId;
        this.farmId = farmId;
        this.warehouseId = warehouseId;
    }

    public String getId() {
        return id;
    }

    public String getTenantId() {
        return tenantId;
    }

    public String getItemId() {
        return itemId;
    }

    public String getFarmId() {
        return farmId;
    }

    public String getWarehouseId() {
        return warehouseId;
    }
}
