import { useState, type FormEvent } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { del, get, post, put } from '../api'
import { Card, Empty, ErrorText, Field, JsonView, Page } from '../ui'
import { useAuth, can } from '../auth'
type Roles = { roles: Record<string, string[]> }
export default function Admin() {
    const { me } = useAuth(), cache = useQueryClient(); const [user, setUser] = useState(''), [role, setRole] = useState('FARM_OPERATOR'), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [error, setError] = useState<unknown>(null), [result, setResult] = useState<unknown>(null)
    const roles = useQuery({ queryKey: ['roles', me?.tenantId], queryFn: () => get<Roles>('/api/v1/admin/roles'), enabled: can(me, 'identity:admin') }); const permissions = useQuery({ queryKey: ['permissions', me?.tenantId], queryFn: () => get<unknown>('/api/v1/admin/permissions'), enabled: can(me, 'identity:admin') }); const userRoles = useQuery({ queryKey: ['user-roles', me?.tenantId, user], queryFn: () => get<unknown>('/api/v1/admin/users/' + encodeURIComponent(user) + '/roles'), enabled: !!user && can(me, 'identity:admin') })
    async function perform(fn: () => Promise<unknown>) { setError(null); try { setResult(await fn()); await Promise.all([cache.invalidateQueries({ queryKey: ['roles'] }), cache.invalidateQueries({ queryKey: ['user-roles'] })]) } catch (e) { setError(e) } }
    function create(e: FormEvent) { e.preventDefault(); void perform(() => post('/api/v1/admin/users', { email, password })) }
    const allowed = Object.keys(roles.data?.roles || {}).filter(x => !['SUPERADMIN', 'PLATFORM_ADMIN'].includes(x))
    return <Page title="Người dùng & quyền" subtitle="Quản trị người dùng trong tenant và cấp role nghiệp vụ."><div className="grid"><Card title="Role hệ thống">{roles.isError ? <ErrorText error={roles.error} /> : roles.data ? <JsonView value={roles.data} /> : <Empty />}</Card><Card title="Danh mục quyền">{permissions.isError ? <ErrorText error={permissions.error} /> : permissions.data ? <JsonView value={permissions.data} /> : <Empty />}</Card></div><div className="grid"><Card title="Tạo người dùng"><form className="stack" onSubmit={create}><Field label="Email"><input type="email" required value={email} onChange={e => setEmail(e.target.value)} /></Field><Field label="Mật khẩu ban đầu"><input type="password" minLength={12} required value={password} onChange={e => setPassword(e.target.value)} /></Field><button>Tạo người dùng</button></form></Card><Card title="Cấp / gỡ role"><div className="stack"><Field label="User ID"><input value={user} onChange={e => setUser(e.target.value)} /></Field><Field label="Role"><select value={role} onChange={e => setRole(e.target.value)}>{allowed.length ? allowed.map(r => <option key={r}>{r}</option>) : <option>FARM_OPERATOR</option>}</select></Field><div className="actions"><button disabled={!user} onClick={() => perform(() => put('/api/v1/admin/users/' + encodeURIComponent(user) + '/roles/' + encodeURIComponent(role)))}>Cấp role</button><button className="danger-btn" disabled={!user} onClick={() => perform(() => del('/api/v1/admin/users/' + encodeURIComponent(user) + '/roles/' + encodeURIComponent(role)))}>Gỡ role</button></div>{userRoles.data && <JsonView value={userRoles.data} />}<ErrorText error={userRoles.error} /></div></Card></div><ErrorText error={error} />{result !== null && <p className="success-msg">Kết quả: {JSON.stringify(result)}</p>}</Page>
}
