import { useState, type FormEvent } from 'react'
import { useQuery } from '@tanstack/react-query'
import { gql, money } from '../api'
import { Card, Empty, ErrorText, Field, Page } from '../ui'
import { useAuth, can } from '../auth'
import { useFarm } from '../app'
type Cost = { batchCost: { feedCost: { currency: string; minor: number }; medicineCost: { currency: string; minor: number }; laborCost: { currency: string; minor: number }; otherCost: { currency: string; minor: number }; totalCost: { currency: string; minor: number }; animalCount: number } }
type Flow = { cashFlow: { farmId: string; inflow: { currency: string; minor: number }; outflow: { currency: string; minor: number }; net: { currency: string; minor: number } } }
type Low = { lowStock: { itemId: string; warehouseId: string; onHand: { value: string; unit: string }; available: { value: string; unit: string } }[] }
export default function Finance() {
    const { farmId } = useFarm(), { me } = useAuth(); const [batch, setBatch] = useState(''), [chosen, setChosen] = useState(''), [from, setFrom] = useState(''), [to, setTo] = useState(''); const cost = useQuery({ queryKey: ['cost', me?.tenantId, farmId, chosen], queryFn: () => gql<Cost>('query($f:ID!,$b:ID!){batchCost(farmId:$f,batchId:$b){feedCost{currency minor} medicineCost{currency minor} laborCost{currency minor} otherCost{currency minor} totalCost{currency minor} animalCount}}', { f: farmId, b: chosen }), enabled: !!farmId && !!chosen && can(me, 'report:read') }); const flow = useQuery({ queryKey: ['flow', me?.tenantId, farmId, from, to], queryFn: () => gql<Flow>('query($f:ID!,$from:Float,$to:Float){cashFlow(farmId:$f,fromEpochMs:$from,toEpochMs:$to){farmId inflow{currency minor} outflow{currency minor} net{currency minor}}}', { f: farmId, from: from ? new Date(from).getTime() : null, to: to ? new Date(to).getTime() : null }), enabled: !!farmId && can(me, 'report:read') }); const low = useQuery({ queryKey: ['low', me?.tenantId, farmId], queryFn: () => gql<Low>('query($f:ID!){lowStock(farmId:$f,limit:20){itemId warehouseId onHand{value unit} available{value unit}}}', { f: farmId }), enabled: !!farmId && can(me, 'inventory:read') })
    function choose(e: FormEvent) { e.preventDefault(); setChosen(batch) }
    return <Page title="Chi phí & dòng tiền" subtitle="Các read-model GraphQL từ Gateway; không có thao tác ghi sổ tài chính."><div className="grid"><Card title="Chi phí theo lô"><form className="filters" onSubmit={choose}><Field label="Batch ID"><input required value={batch} onChange={e => setBatch(e.target.value)} /></Field><button disabled={!farmId}>Xem</button></form>{cost.isError ? <ErrorText error={cost.error} /> : cost.data ? <div className="stack"><b>Tổng: {money(cost.data.batchCost.totalCost.minor, cost.data.batchCost.totalCost.currency)}</b><span>Thức ăn: {money(cost.data.batchCost.feedCost.minor)}</span><span>Thuốc: {money(cost.data.batchCost.medicineCost.minor)}</span><span>Nhân công: {money(cost.data.batchCost.laborCost.minor)}</span><span>Số vật nuôi: {cost.data.batchCost.animalCount}</span></div> : <Empty text="Nhập mã lô." />}</Card><Card title="Dòng tiền"><div className="filters"><Field label="Từ"><input type="datetime-local" value={from} onChange={e => setFrom(e.target.value)} /></Field><Field label="Đến"><input type="datetime-local" value={to} onChange={e => setTo(e.target.value)} /></Field></div>{flow.isError ? <ErrorText error={flow.error} /> : flow.data ? <div className="stack"><b>Ròng: {money(flow.data.cashFlow.net.minor, flow.data.cashFlow.net.currency)}</b><span>Thu: {money(flow.data.cashFlow.inflow.minor)}</span><span>Chi: {money(flow.data.cashFlow.outflow.minor)}</span></div> : <Empty />}</Card></div><Card title="Điểm tồn kho thấp">{low.isError ? <ErrorText error={low.error} /> : low.data?.lowStock.length ? low.data.lowStock.map((s, i) => <div className="row" key={i}><div><b>{s.itemId}</b><small>Kho: {s.warehouseId}</small></div><span>{s.available.value} {s.available.unit}</span></div>) : <Empty />}</Card></Page>
}
