import { useState, type FormEvent } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { get, params, post, time, type Schedule } from '../api'
import { Card, Empty, ErrorText, Field, Page } from '../ui'
import { useAuth, can } from '../auth'
import { useFarm } from '../app'
export default function Schedules() {
    const { farmId } = useFarm(), { me } = useAuth(), cache = useQueryClient(); const [title, setTitle] = useState(''), [cron, setCron] = useState('0 0 7 * * *'), [zone, setZone] = useState('Asia/Ho_Chi_Minh'), [type, setType] = useState('FEEDING'), [assignee, setAssignee] = useState(''), [error, setError] = useState<unknown>(null)
    const q = useQuery({ queryKey: ['schedules', me?.tenantId, farmId], queryFn: () => get<Schedule[] | { schedules: Schedule[] }>(params('/api/v1/livestock/schedules', { farmId, limit: 50 })), enabled: !!farmId && can(me, 'farm:read') }); const rows = Array.isArray(q.data) ? q.data : q.data?.schedules || []
    async function submit(e: FormEvent) { e.preventDefault(); setError(null); try { await post('/api/v1/livestock/schedules', { farmId, title, type, cronExpression: cron, timeZone: zone, assigneeId: assignee || undefined, enabled: true }); setTitle(''); await cache.invalidateQueries({ queryKey: ['schedules'] }) } catch (e) { setError(e) } }
    return <Page title="Lịch công việc" subtitle="Lịch cron 6 trường theo múi giờ IANA."><Card title="Lịch hiện tại">{q.isError ? <ErrorText error={q.error} /> : q.isLoading ? <Empty text="Đang tải..." /> : rows.length ? rows.map(s => <div className="row" key={s.scheduleId}><div><b>{s.title}</b><small>{s.cronExpression} · {s.timeZone} · {s.enabled ? 'Đang bật' : 'Đã tắt'}</small></div><span>Lần tới: {time(s.nextRunAt)}</span></div>) : <Empty />}</Card>{can(me, 'tasks:write') && <Card title="Tạo lịch"><form className="form-grid" onSubmit={submit}><Field label="Tiêu đề"><input required value={title} onChange={e => setTitle(e.target.value)} /></Field><Field label="Loại"><select value={type} onChange={e => setType(e.target.value)}>{['FEEDING', 'CLEANING', 'INSPECTION', 'MEDICATION', 'OTHER'].map(t => <option key={t}>{t}</option>)}</select></Field><Field label="Cron (giây phút giờ ngày tháng thứ)"><input required value={cron} onChange={e => setCron(e.target.value)} /></Field><Field label="Múi giờ"><input required value={zone} onChange={e => setZone(e.target.value)} /></Field><Field label="Người phụ trách"><input value={assignee} onChange={e => setAssignee(e.target.value)} /></Field><button disabled={!farmId}>Tạo lịch</button></form></Card>}<ErrorText error={error} /></Page>
}
