import { useState, type FormEvent } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { get, newKey, params, post, time, type Task } from '../api'
import { Card, Empty, ErrorText, Field, Page, Status } from '../ui'
import { useAuth, can } from '../auth'
import { useFarm } from '../app'
const TYPES = ['FEEDING', 'CLEANING', 'INSPECTION', 'MEDICATION', 'OTHER']
export default function Tasks() {
    const { farmId } = useFarm(), { me } = useAuth(), cache = useQueryClient(); const [title, setTitle] = useState(''), [type, setType] = useState('OTHER'), [assignee, setAssignee] = useState(''), [due, setDue] = useState(''), [status, setStatus] = useState(''), [selected, setSelected] = useState(''), [input, setInput] = useState(''), [note, setNote] = useState(''), [error, setError] = useState<unknown>(null), [busy, setBusy] = useState(false)
    const list = useQuery({ queryKey: ['tasks', me?.tenantId, farmId, status], queryFn: () => get<Task[] | { tasks: Task[] }>(params('/api/v1/livestock/tasks', { farmId, status, limit: 50 })), enabled: !!farmId && can(me, 'farm:read') }); const tasks = Array.isArray(list.data) ? list.data : list.data?.tasks || []
    const detail = useQuery({ queryKey: ['task', me?.tenantId, selected], queryFn: () => get<Task>('/api/v1/livestock/tasks/' + encodeURIComponent(selected)), enabled: !!selected && can(me, 'farm:read') })
    async function create(e: FormEvent) { e.preventDefault(); setError(null); setBusy(true); try { const result = await post<Task>('/api/v1/livestock/tasks', { farmId, title, type, assigneeId: assignee || undefined, dueAtEpochMs: due ? new Date(due).getTime() : undefined }, newKey()); setTitle(''); setSelected(result.taskId); await cache.invalidateQueries({ queryKey: ['tasks'] }) } catch (e) { setError(e) } finally { setBusy(false) } }
    async function action(kind: 'assign' | 'accept' | 'complete' | 'cancel') { if (!selected) return; setBusy(true); setError(null); try { const body = kind === 'assign' ? { assigneeId: input } : kind === 'complete' ? { note } : kind === 'cancel' ? { reason: note } : undefined; await post(`/api/v1/livestock/tasks/${encodeURIComponent(selected)}/${kind}`, body); await Promise.all([cache.invalidateQueries({ queryKey: ['tasks'] }), cache.invalidateQueries({ queryKey: ['task', me?.tenantId, selected] }), cache.invalidateQueries({ queryKey: ['dashboard'] })]) } catch (e) { setError(e) } finally { setBusy(false) } }
    return <Page title="Công việc chăn nuôi" subtitle="Tạo, giao, nhận và theo dõi vòng đời nhiệm vụ."><div className="grid"><Card title="Danh sách"><div className="filters"><Field label="Trạng thái"><select value={status} onChange={e => setStatus(e.target.value)}><option value="">Tất cả</option>{['CREATED', 'ASSIGNED', 'ACCEPTED', 'COMPLETED', 'CANCELLED'].map(s => <option key={s}>{s}</option>)}</select></Field></div>{!farmId ? <Empty text="Nhập mã trang trại ở thanh trên." /> : list.isLoading ? <Empty text="Đang tải..." /> : list.isError ? <ErrorText error={list.error} /> : tasks.length ? tasks.map(t => <button className={'row row-btn ' + (selected === t.taskId ? 'selected' : '')} key={t.taskId} onClick={() => setSelected(t.taskId)}><span><b>{t.title}</b><small>{t.assigneeId || 'Chưa giao'} · {t.taskId}</small></span><Status value={t.status} /></button>) : <Empty />}</Card><Card title="Chi tiết / thao tác">{detail.isError ? <ErrorText error={detail.error} /> : detail.data ? <><div className="detail"><p><b>{detail.data.title}</b> · <Status value={detail.data.status} /></p><p>Loại: {detail.data.type || '—'} · Người nhận: {detail.data.assigneeId || '—'}</p><p>Hạn nhận: {time(detail.data.acceptDeadlineAt)} · Hạn báo cáo: {time(detail.data.reportDueAt)}</p><p>Hạn hoàn thành: {time(detail.data.dueAt)}</p></div>{can(me, 'tasks:write') && <div className="stack"><Field label="Người được giao"><input value={input} onChange={e => setInput(e.target.value)} /></Field><Field label="Ghi chú / lý do"><input value={note} onChange={e => setNote(e.target.value)} /></Field><div className="actions"><button disabled={busy || !input} onClick={() => action('assign')}>Giao việc</button><button disabled={busy} onClick={() => action('accept')}>Nhận</button><button disabled={busy} onClick={() => action('complete')}>Hoàn thành</button><button className="danger-btn" disabled={busy} onClick={() => action('cancel')}>Hủy</button></div></div>}</> : <Empty text="Chọn nhiệm vụ để xem chi tiết." />}</Card></div>
        {can(me, 'tasks:write') && <Card title="Tạo nhiệm vụ"><form className="form-grid" onSubmit={create}><Field label="Tiêu đề"><input required maxLength={200} value={title} onChange={e => setTitle(e.target.value)} /></Field><Field label="Loại"><select value={type} onChange={e => setType(e.target.value)}>{TYPES.map(x => <option key={x}>{x}</option>)}</select></Field><Field label="Người nhận (tùy chọn)"><input value={assignee} onChange={e => setAssignee(e.target.value)} /></Field><Field label="Hạn (tùy chọn)"><input type="datetime-local" value={due} onChange={e => setDue(e.target.value)} /></Field><button disabled={busy || !farmId}>Tạo nhiệm vụ</button></form></Card>}<ErrorText error={error} /></Page>
}
