package com.htv.smartfarm.gateway.order;

import com.google.protobuf.Timestamp;
import com.htv.smartfarm.gateway.context.GatewayCorrelationContext;
import com.htv.smartfarm.gateway.grpc.GatewayGrpcExceptionMapper;
import com.htv.smartfarm.gateway.identity.GatewayRequestContextFactory;
import com.htv.smartfarm.gateway.identity.ServiceTokenClient;
import com.htv.smartfarm.proto.common.v1.*;
import com.htv.smartfarm.proto.order.v1.*;
import com.htv.smartfarm.security.grpc.BearerCallCredentials;
import io.grpc.StatusRuntimeException;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import java.time.Instant;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.TimeUnit;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.web.bind.annotation.*;
import reactor.core.publisher.Mono;
import reactor.core.scheduler.Schedulers;

@RestController
@RequestMapping("/api/v1/orders")
@Tag(name = "Orders", description = "Order placement, draft lifecycle, cursor pagination and cancellation")
public class OrderRestController {
    public record Line(String itemId,String quantity,String unit,String currency,Long unitPriceMinor,String warehouseId){}
    public record Create(String farmId,String batchId,List<Line> lines){}
    public record Update(String farmId,String batchId,long expectedVersion,List<Line> lines){}
    public record Version(long expectedVersion){}
    public record Cancel(String reason){}
    private static final String AUDIENCE="smartfarm-order";
    private final FarmOrderServiceGrpc.FarmOrderServiceBlockingStub base; private final ServiceTokenClient tokens;
    private final GatewayRequestContextFactory contexts; private final GatewayGrpcExceptionMapper errors; private final long deadlineMillis;
    public OrderRestController(FarmOrderServiceGrpc.FarmOrderServiceBlockingStub base,ServiceTokenClient tokens,GatewayRequestContextFactory contexts,GatewayGrpcExceptionMapper errors,@Value("${smartfarm.gateway.grpc.order-deadline:5s}") Duration deadline){this.base=base;this.tokens=tokens;this.contexts=contexts;this.errors=errors;this.deadlineMillis=positive(deadline,"order deadline");}

    @PostMapping @PreAuthorize("hasAuthority('SCOPE_orders:write')") public Mono<Map<String,Object>> place(@AuthenticationPrincipal Jwt jwt,@Parameter(description="Required idempotency key", required=true) @RequestHeader("Idempotency-Key") String key,@Parameter(description="Optional correlation ID, echoed in the response") @RequestHeader(value="X-Correlation-Id",required=false) String correlation,@RequestBody Create body){return call("PlaceOrder",jwt,()->{var c=contexts.create(jwt,corr(correlation),required(key,"Idempotency-Key"));var b=PlaceOrderRequest.newBuilder().setContext(c).setFarmId(required(body.farmId(),"farmId"));optional(body.batchId(),b::setBatchId);lines(body.lines()).forEach(b::addLines);return view(stub(jwt,c.getCorrelationId()).placeOrder(b.build()).getOrder());});}
    @PostMapping("/drafts") @PreAuthorize("hasAuthority('SCOPE_orders:write')") public Mono<Map<String,Object>> createDraft(@AuthenticationPrincipal Jwt jwt,@Parameter(description="Required idempotency key", required=true) @RequestHeader("Idempotency-Key") String key,@Parameter(description="Optional correlation ID, echoed in the response") @RequestHeader(value="X-Correlation-Id",required=false) String correlation,@RequestBody Create body){return call("CreateDraftOrder",jwt,()->{var c=contexts.create(jwt,corr(correlation),required(key,"Idempotency-Key"));var b=CreateDraftOrderRequest.newBuilder().setContext(c).setFarmId(required(body.farmId(),"farmId"));optional(body.batchId(),b::setBatchId);lines(body.lines()).forEach(b::addLines);return view(stub(jwt,c.getCorrelationId()).createDraftOrder(b.build()).getOrder());});}
    @PutMapping("/drafts/{id}") @PreAuthorize("hasAuthority('SCOPE_orders:write')") public Mono<Map<String,Object>> updateDraft(@AuthenticationPrincipal Jwt jwt,@Parameter(description="Optional correlation ID, echoed in the response") @RequestHeader(value="X-Correlation-Id",required=false) String correlation,@PathVariable String id,@RequestBody Update body){return call("UpdateDraftOrder",jwt,()->{var c=contexts.create(jwt,corr(correlation),null);var b=UpdateDraftOrderRequest.newBuilder().setContext(c).setOrderId(id).setExpectedVersion(body.expectedVersion()).setFarmId(required(body.farmId(),"farmId"));optional(body.batchId(),b::setBatchId);lines(body.lines()).forEach(b::addLines);return view(stub(jwt,c.getCorrelationId()).updateDraftOrder(b.build()).getOrder());});}
    @PostMapping("/drafts/{id}/submit") @PreAuthorize("hasAuthority('SCOPE_orders:write')") public Mono<Map<String,Object>> submit(@AuthenticationPrincipal Jwt jwt,@Parameter(description="Optional correlation ID, echoed in the response") @RequestHeader(value="X-Correlation-Id",required=false) String correlation,@PathVariable String id,@RequestBody Version body){return call("SubmitDraftOrder",jwt,()->{var c=contexts.create(jwt,corr(correlation),null);return view(stub(jwt,c.getCorrelationId()).submitDraftOrder(SubmitDraftOrderRequest.newBuilder().setContext(c).setOrderId(id).setExpectedVersion(body.expectedVersion()).build()).getOrder());});}
    @DeleteMapping("/drafts/{id}") @PreAuthorize("hasAuthority('SCOPE_orders:write')") public Mono<Void> delete(@AuthenticationPrincipal Jwt jwt,@Parameter(description="Optional correlation ID, echoed in the response") @RequestHeader(value="X-Correlation-Id",required=false) String correlation,@PathVariable String id,@RequestParam long expectedVersion){return call("DeleteDraftOrder",jwt,()->{var c=contexts.create(jwt,corr(correlation),null);stub(jwt,c.getCorrelationId()).deleteDraftOrder(DeleteDraftOrderRequest.newBuilder().setContext(c).setOrderId(id).setExpectedVersion(expectedVersion).build());return true;}).then();}
    @GetMapping("/{id}") @PreAuthorize("hasAuthority('SCOPE_orders:read')") public Mono<Map<String,Object>> get(@AuthenticationPrincipal Jwt jwt,@Parameter(description="Optional correlation ID, echoed in the response") @RequestHeader(value="X-Correlation-Id",required=false) String correlation,@PathVariable String id){return call("GetOrder",jwt,()->{var c=contexts.create(jwt,corr(correlation),null);return view(stub(jwt,c.getCorrelationId()).getOrder(GetOrderRequest.newBuilder().setContext(c).setOrderId(id).build()).getOrder());});}
    @GetMapping @PreAuthorize("hasAuthority('SCOPE_orders:read')") public Mono<Map<String,Object>> list(@AuthenticationPrincipal Jwt jwt,@Parameter(description="Optional correlation ID, echoed in the response") @RequestHeader(value="X-Correlation-Id",required=false) String correlation,@RequestParam(required=false) String farmId,@RequestParam(required=false) String status,@RequestParam(required=false) String warehouseId,@RequestParam(defaultValue="20") int size,@RequestParam(defaultValue="") String pageToken){return call("ListOrders",jwt,()->{var c=contexts.create(jwt,corr(correlation),null);var b=ListOrdersRequest.newBuilder().setContext(c).setPage(PageRequest.newBuilder().setPageSize(Math.max(1,Math.min(size,100))).setPageToken(pageToken));optional(farmId,b::setFarmId);optional(warehouseId,b::setWarehouseId);if(status!=null&&!status.isBlank())b.setStatus(orderStatus(status));var r=stub(jwt,c.getCorrelationId()).listOrders(b.build());return Map.of("orders",r.getOrdersList().stream().map(OrderRestController::view).toList(),"nextPageToken",r.getPage().getNextPageToken());});}
    @PostMapping("/{id}/cancel") @PreAuthorize("hasAuthority('SCOPE_orders:write')") public Mono<Map<String,Object>> cancel(@AuthenticationPrincipal Jwt jwt,@Parameter(description="Optional correlation ID, echoed in the response") @RequestHeader(value="X-Correlation-Id",required=false) String correlation,@PathVariable String id,@RequestBody(required=false) Cancel body){return call("CancelOrder",jwt,()->{var c=contexts.create(jwt,corr(correlation),null);var b=CancelOrderRequest.newBuilder().setContext(c).setOrderId(id);if(body!=null)optional(body.reason(),b::setReason);return view(stub(jwt,c.getCorrelationId()).cancelOrder(b.build()).getOrder());});}

    private FarmOrderServiceGrpc.FarmOrderServiceBlockingStub stub(Jwt jwt,String correlation){String tenant=required(jwt.getClaimAsString("tenant_id"),"tenantId");String token=tokens.tokenFor(AUDIENCE,tenant,jwt.getSubject());return base.withDeadlineAfter(deadlineMillis,TimeUnit.MILLISECONDS).withCallCredentials(new BearerCallCredentials(()->token,()->tenant,()->correlation));}
    private <T>Mono<T> call(String op,Jwt jwt,java.util.concurrent.Callable<T> fn){return Mono.fromCallable(()->{try{return fn.call();}catch(StatusRuntimeException e){if(e.getStatus().getCode()==io.grpc.Status.Code.UNAUTHENTICATED)tokens.invalidate(AUDIENCE,jwt.getClaimAsString("tenant_id"));throw errors.rest(op,e);}}).subscribeOn(Schedulers.boundedElastic());}
    private String corr(String v){return GatewayCorrelationContext.normalize(v);} private static List<OrderLine> lines(List<Line> values){if(values==null||values.isEmpty())throw new IllegalArgumentException("lines must not be empty");return values.stream().map(v->{var b=OrderLine.newBuilder().setItemId(required(v.itemId(),"itemId")).setQuantity(Quantity.newBuilder().setDecimalValue(required(v.quantity(),"quantity")).setUnit(required(v.unit(),"unit"))).setUnitPrice(Money.newBuilder().setCurrencyCode(required(v.currency(),"currency")).setMinorUnits(requiredPositive(v.unitPriceMinor(),"unitPriceMinor")));optional(v.warehouseId(),b::setWarehouseId);return b.build();}).toList();}
    public static Map<String,Object> view(FarmOrder o){Map<String,Object>m=new LinkedHashMap<>();m.put("orderId",o.getOrderId());m.put("farmId",o.getFarmId());m.put("batchId",blank(o.getBatchId()));m.put("status",o.getStatus().name());m.put("totalMinor",o.getTotal().getMinorUnits());m.put("currency",o.getTotal().getCurrencyCode());m.put("version",o.getVersion());m.put("createdAt",o.hasCreatedAt()?ts(o.getCreatedAt()):null);m.put("updatedAt",o.hasUpdatedAt()?ts(o.getUpdatedAt()):null);m.put("failureReason",blank(o.getFailureReason()));m.put("lines",o.getLinesList().stream().map(OrderRestController::line).toList());return m;}
    private static Map<String,Object> line(OrderLine l){Map<String,Object>m=new LinkedHashMap<>();m.put("lineId",l.getLineId());m.put("lineNo",l.getLineNo());m.put("itemId",l.getItemId());m.put("warehouseId",blank(l.getWarehouseId()));m.put("quantity",l.getQuantity().getDecimalValue());m.put("unit",l.getQuantity().getUnit());m.put("unitPriceMinor",l.getUnitPrice().getMinorUnits());m.put("currency",l.getUnitPrice().getCurrencyCode());m.put("lineTotalMinor",l.getLineTotalMinor());m.put("version",l.getVersion());return m;}
    private static long requiredPositive(Long v,String f){if(v==null||v<=0)throw new IllegalArgumentException(f+" must be positive");return v;} private static long positive(Duration v,String f){if(v==null||v.isZero()||v.isNegative())throw new IllegalArgumentException(f+" must be positive");return v.toMillis();} private static OrderStatus orderStatus(String v){String n=v.toUpperCase();return OrderStatus.valueOf(n.startsWith("ORDER_STATUS_")?n:"ORDER_STATUS_"+n);} private static String ts(Timestamp v){return Instant.ofEpochSecond(v.getSeconds(),v.getNanos()).toString();} private static String blank(String v){return v==null||v.isBlank()?null:v;} private static String required(String v,String f){if(v==null||v.isBlank())throw new IllegalArgumentException(f+" is required");return v.trim();} private static void optional(String v,java.util.function.Consumer<String> c){if(v!=null&&!v.isBlank())c.accept(v.trim());}
}
