package com.htv.smartfarm.health.store;

import java.util.List;

import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Repository;

import com.google.protobuf.InvalidProtocolBufferException;
import com.htv.smartfarm.health.outbox.HealthOutboxEntity;
import com.htv.smartfarm.health.outbox.HealthOutboxJpaRepository;
import com.htv.smartfarm.proto.health.v1.HealthObservation;
import com.htv.smartfarm.proto.health.v1.Vaccination;

/**
 * Persistence facade for health aggregates and the outbox row. Backed by Spring
 * Data JPA; schema is generated by Hibernate. Public method signatures are
 * unchanged from the former JdbcTemplate implementation so callers are unaffected.
 * Payloads are stored as serialized protobuf bytes, exactly as before.
 */
@Repository
public class HealthStore {

    private final ObservationJpaRepository observationsRepo;
    private final VaccinationJpaRepository vaccinationsRepo;
    private final HealthOutboxJpaRepository outboxRepo;

    public HealthStore(ObservationJpaRepository observationsRepo, VaccinationJpaRepository vaccinationsRepo,
                       HealthOutboxJpaRepository outboxRepo) {
        this.observationsRepo = observationsRepo;
        this.vaccinationsRepo = vaccinationsRepo;
        this.outboxRepo = outboxRepo;
    }

    public HealthObservation observationByKey(String tenant, String key) {
        return observationsRepo.findByTenantIdAndIdempotencyKey(tenant, key)
                .map(e -> parseObservation(e.getPayload()))
                .orElse(null);
    }

    public void saveObservation(String tenant, String key, HealthObservation o) {
        observationsRepo.save(new ObservationEntity(o.getObservationId(), tenant, o.getAnimalId(),
                o.getFarmId(), o.getObservedAt().getSeconds(), key, o.toByteArray()));
    }

    public List<HealthObservation> observations(String tenant, String animal, int limit) {
        return observationsRepo
                .findByTenantIdAndAnimalIdOrderByObservedAtDescIdDesc(tenant, animal, PageRequest.of(0, limit))
                .stream().map(e -> parseObservation(e.getPayload())).toList();
    }

    public Vaccination vaccinationByKey(String tenant, String key) {
        return vaccinationsRepo.findByTenantIdAndIdempotencyKey(tenant, key)
                .map(e -> parseVaccination(e.getPayload()))
                .orElse(null);
    }

    public void saveVaccination(String tenant, String key, Vaccination v) {
        vaccinationsRepo.save(new VaccinationEntity(v.getVaccinationId(), tenant, v.getAnimalId(),
                v.getAdministeredAt().getSeconds(), key, v.toByteArray()));
    }

    public List<Vaccination> vaccinations(String tenant, String animal, int limit) {
        return vaccinationsRepo
                .findByTenantIdAndAnimalIdOrderByAdministeredAtDescIdDesc(tenant, animal, PageRequest.of(0, limit))
                .stream().map(e -> parseVaccination(e.getPayload())).toList();
    }

    public void saveOutbox(String eventId, String tenant, String farm, String id, String type, byte[] payload) {
        outboxRepo.save(new HealthOutboxEntity(eventId, tenant, farm, id, type, payload, "NEW"));
    }

    private static HealthObservation parseObservation(byte[] b) {
        try {
            return HealthObservation.parseFrom(b);
        } catch (InvalidProtocolBufferException e) {
            throw new IllegalStateException("Corrupt observation", e);
        }
    }

    private static Vaccination parseVaccination(byte[] b) {
        try {
            return Vaccination.parseFrom(b);
        } catch (InvalidProtocolBufferException e) {
            throw new IllegalStateException("Corrupt vaccination", e);
        }
    }
}
