package com.htv.smartfarm.health.store;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Lob;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/** JPA mapping of {@code h_observation}. Schema generated by Hibernate (ddl-auto). */
@Entity
@Table(name = "h_observation",
        uniqueConstraints = @UniqueConstraint(name = "uq_h_obs_idem", columnNames = {"tenant_id", "idempotency_key"}),
        indexes = @Index(name = "idx_h_obs_tenant_animal", columnList = "tenant_id,animal_id,observed_at"))
public class ObservationEntity {

    @Id
    @Column(length = 36)
    private String id;

    @Column(name = "tenant_id", nullable = false, length = 100)
    private String tenantId;

    @Column(name = "animal_id", nullable = false, length = 100)
    private String animalId;

    @Column(name = "farm_id", nullable = false, length = 100)
    private String farmId;

    @Column(name = "observed_at", nullable = false)
    private long observedAt;

    @Column(name = "idempotency_key", nullable = false, length = 128)
    private String idempotencyKey;

    @Lob
    @Column(nullable = false)
    private byte[] payload;

    protected ObservationEntity() {
    }

    public ObservationEntity(String id, String tenantId, String animalId, String farmId, long observedAt,
                             String idempotencyKey, byte[] payload) {
        this.id = id;
        this.tenantId = tenantId;
        this.animalId = animalId;
        this.farmId = farmId;
        this.observedAt = observedAt;
        this.idempotencyKey = idempotencyKey;
        this.payload = payload;
    }

    public byte[] getPayload() {
        return payload;
    }
}
