package com.htv.smartfarm.health.store;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Lob;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/** JPA mapping of {@code h_vaccination}. Schema generated by Hibernate (ddl-auto). */
@Entity
@Table(name = "h_vaccination",
        uniqueConstraints = @UniqueConstraint(name = "uq_h_vax_idem", columnNames = {"tenant_id", "idempotency_key"}),
        indexes = @Index(name = "idx_h_vax_tenant_animal", columnList = "tenant_id,animal_id,administered_at"))
public class VaccinationEntity {

    @Id
    @Column(length = 36)
    private String id;

    @Column(name = "tenant_id", nullable = false, length = 100)
    private String tenantId;

    @Column(name = "animal_id", nullable = false, length = 100)
    private String animalId;

    @Column(name = "administered_at", nullable = false)
    private long administeredAt;

    @Column(name = "idempotency_key", nullable = false, length = 128)
    private String idempotencyKey;

    @Lob
    @Column(nullable = false)
    private byte[] payload;

    protected VaccinationEntity() {
    }

    public VaccinationEntity(String id, String tenantId, String animalId, long administeredAt,
                             String idempotencyKey, byte[] payload) {
        this.id = id;
        this.tenantId = tenantId;
        this.animalId = animalId;
        this.administeredAt = administeredAt;
        this.idempotencyKey = idempotencyKey;
        this.payload = payload;
    }

    public byte[] getPayload() {
        return payload;
    }
}
