package com.htv.smartfarm.livestock.schedule;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;

/**
 * JPA mapping of {@code sf_task_schedule} — a recurring task template. {@code cronExpression}
 * is evaluated in {@code timeZone} (never assume server TZ / DST) to compute {@code nextRunAt}.
 * A future scheduler wakes on {@code nextRunAt} to materialise a concrete task, then advances
 * it. Schema is generated by Hibernate ({@code ddl-auto}).
 */
@Entity
@Table(name = "sf_task_schedule",
        indexes = {
                @Index(name = "ix_sched_farm", columnList = "tenant_id,farm_id"),
                @Index(name = "ix_sched_due", columnList = "enabled,next_run_at")
        })
public class ScheduleEntity {

    @Id
    @Column(name = "schedule_id", length = 36)
    private String id;

    @Column(name = "tenant_id", nullable = false, length = 100)
    private String tenantId;

    @Column(name = "farm_id", nullable = false, length = 100)
    private String farmId;

    @Column(name = "title", nullable = false, length = 200)
    private String title;

    /**
     * TaskType enum name applied to tasks this schedule creates.
     */
    @Column(name = "task_type", length = 40)
    private String taskType;

    @Column(name = "cron_expression", nullable = false, length = 120)
    private String cronExpression;

    @Column(name = "time_zone", nullable = false, length = 60)
    private String timeZone;

    @Column(name = "assignee_id", length = 100)
    private String assigneeId;

    @Column(name = "enabled", nullable = false)
    private boolean enabled;

    @Column(name = "next_run_at")
    private Long nextRunAt; // epoch millis

    @Column(name = "created_at", nullable = false)
    private long createdAt;

    protected ScheduleEntity() {
    }

    public ScheduleEntity(String id, String tenantId, String farmId, String title, String taskType,
                          String cronExpression, String timeZone, String assigneeId, boolean enabled,
                          Long nextRunAt, long createdAt) {
        this.id = id;
        this.tenantId = tenantId;
        this.farmId = farmId;
        this.title = title;
        this.taskType = taskType;
        this.cronExpression = cronExpression;
        this.timeZone = timeZone;
        this.assigneeId = assigneeId;
        this.enabled = enabled;
        this.nextRunAt = nextRunAt;
        this.createdAt = createdAt;
    }

    public String getId() {
        return id;
    }

    public String getTenantId() {
        return tenantId;
    }

    public String getFarmId() {
        return farmId;
    }

    public String getTitle() {
        return title;
    }

    public String getTaskType() {
        return taskType;
    }

    public String getCronExpression() {
        return cronExpression;
    }

    public String getTimeZone() {
        return timeZone;
    }

    public String getAssigneeId() {
        return assigneeId;
    }

    public boolean isEnabled() {
        return enabled;
    }

    public Long getNextRunAt() {
        return nextRunAt;
    }

    public long getCreatedAt() {
        return createdAt;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public void setNextRunAt(Long nextRunAt) {
        this.nextRunAt = nextRunAt;
    }
}
